### ISSUE TITLE
webui: history reset not working

### ISSUE THREAD

**Issue by sschimi** [rspamd/rspamd#2346]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.8

### Description (Please provide a descriptive summary of the issue):
Resetting the history via WebUI is not working. Page is just reloading without emptying the history

### Compile errors (if any):
No compile errors neither log errors

### Steps to reproduce:
WebUI: Click on history / click on reset.

### Expected results:
Empty History

**Comment by moisseev** [comment]
It seems now history reset works only for individual servers, not for the whole cluster.
https://github.com/vstakhov/rspamd/blob/ab72e301244e22f10463bfbf744ad95da4f7e9f9/interface/js/app/history.js#L684-L689
@vstakhov Did you do it on purpose?

Another problem: I get segfault when I try to reset history from WebUI.

```cxx
# gdb `which rspamd` -c /coreland/rspamd-1.7.9.core
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...

warning: core file may not match specified executable file.
Core was generated by `rspamd: controller process (*:11334)'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/libhs.so.4...done.
Loaded symbols for /usr/local/lib/libhs.so.4
Reading symbols from /lib/libutil.so.9...done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libevent-2.1.so.6...done.
Loaded symbols for /usr/local/lib/libevent-2.1.so.6
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libicui18n.so.62...done.
Loaded symbols for /usr/local/lib/libicui18n.so.62
Reading symbols from /usr/local/lib/libicuuc.so.62...done.
Loaded symbols for /usr/local/lib/libicuuc.so.62
Reading symbols from /usr/local/lib/libicudata.so.62...
warning: Lowest section in /usr/local/lib/libicudata.so.62 is .hash at 0000000000000120
done.
Loaded symbols for /usr/local/lib/libicudata.so.62
Reading symbols from /lib/libcrypto.so.8...done.
Loaded symbols for /lib/libcrypto.so.8
Reading symbols from /usr/lib/libssl.so.8...done.
Loaded symbols for /usr/lib/libssl.so.8
Reading symbols from /usr/lib/libmagic.so.4...done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libz.so.6...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /usr/lib/libc++.so.1...done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x000000080454e1bf in strlen () from /lib/libc.so.7
(gdb) bt full
#0  0x000000080454e1bf in strlen () from /lib/libc.so.7
No symbol table info available.
#1  0x000000000052cba9 in rspamd_controller_send_string (entry=0x80543a840, str=0x0) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-86c9af0/src/libserver/worker_util.c:452
        msg = (struct rspamd_http_message *) 0x806523280
        reply = (rspamd_fstring_t *) 0x80543a840
#2  0x000000000041ba4c in lua_csession_send_string (L=0x1a1378) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-86c9af0/src/controller.c:3469
        c = (struct rspamd_http_connection_entry *) 0x80543a840
        str = (const gchar *) 0x0
#3  0x000000080417e1d6 in ?? () from /usr/local/lib/libluajit-5.1.so.2
No symbol table info available.
#4  0x000000080418fe91 in lua_pcall () from /usr/local/lib/libluajit-5.1.so.2
No symbol table info available.
#5  0x00000000004bf84c in lua_redis_push_data (r=0x80543a120, ctx=0x8055ec880, sp_ud=0x809bff580) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-86c9af0/src/lua/lua_redis.c:336
        ud = (struct lua_redis_userdata *) 0x8055ec888
#6  0x00000000004bf3ad in lua_redis_callback (c=0x8054cfb80, r=0x80543a120, priv=0x809bff580) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-86c9af0/src/lua/lua_redis.c:387
        reply = (redisReply *) 0x80543a120
        sp_ud = (struct lua_redis_specific_userdata *) 0x809bff580
        ctx = (struct lua_redis_ctx *) 0x8055ec880
        ud = (struct lua_redis_userdata *) 0x8055ec888
        ac = (redisAsyncContext *) 0x7fffffffe140
#7  0x00000000005f142d in redisProcessCallbacks (ac=0x8054cfb80) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-86c9af0/contrib/hiredis/async.c:271
        c = (redisContext *) 0x8054cfb80
        reply = (void *) 0x80543a120
        status = <value optimized out>
#8  0x0000000000534e8a in redisLibeventReadEvent (fd=68, event=2, arg=0x808701080) at libevent.h:45
        e = (redisLibeventEvents *) 0x808701080
#9  0x0000000801e40da0 in event_base_assert_ok_nolock_ () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#10 0x0000000801e3cf4e in event_base_loop () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#11 0x0000000000412c5b in start_controller_worker (worker=0x805421900) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-86c9af0/src/controller.c:3823
        ctx = (struct rspamd_controller_worker_ctx *) 0x80a2057b0
        mctx = (struct module_ctx *) 0x8054b7740
        iter = {dummy1 = 0x806ac7000, dummy2 = 0x427670, dummy3 = 0x7fffffffe3d0, dummy4 = 8, dummy5 = 0, dummy6 = 0x3}
        key = 0x6c4a9f
        value = 0x8087b7820
        cache = (struct rspamd_keypair_cache *) 0x8054eaed8
        stv = {tv_sec = 60, tv_usec = 0}
        save_stats_interval = 60000
        m = 0x740ddac13f3047f8
#12 0x000000000052d272 in rspamd_fork_worker (rspamd_main=0x805433000, cf=0x806dee480, index=0, ev_base=0x8086f3d00)
    at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-86c9af0/src/libserver/worker_util.c:678
        wrk = (struct rspamd_worker *) 0x805421900
        rc = 0
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
#13 0x00000000004276cd in rspamd_fork_delayed_cb (signo=-1, what=1, arg=0x80644fe20) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-86c9af0/src/rspamd.c:330
        w = (struct waiting_worker *) 0x80644fe20
#14 0x0000000801e40da0 in event_base_assert_ok_nolock_ () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#15 0x0000000801e3cf4e in event_base_loop () from /usr/local/lib/libevent-2.1.so.6
No symbol table info available.
#16 0x0000000000424e6a in main (argc=1, argv=0x7fffffffeb98, env=0x7fffffffebd8) at /usr/home/moiseev/git/ports/mail/rspamd-devel/work/rspamd-86c9af0/src/rspamd.c:1475
        i = 1
        res = 0
        signals = {__sigaction_u = {__sa_handler = 0, __sa_sigaction = 0}, sa_flags = 0, sa_mask = {__bits = 0x7fffffffeaf4}}
        sigpipe_act = {__sigaction_u = {__sa_handler = 0x1, __sa_sigaction = 0x1}, sa_flags = 0, sa_mask = {__bits = 0x7fffffffead4}}
        pworker = (worker_t **) 0x953178
        type = 1
        control_addr = (rspamd_inet_addr_t *) 0x8093dc9c0
        ev_base = (struct event_base *) 0x8086f3d00
        term_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x8009329f3, tqe_prev = 0x0}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
---Type <return> to continue, or q <return> to quit---
      evcb_callback = 0x425920 <rspamd_term_handler>, evcb_selfcb = 0x425920 <rspamd_term_handler>, evcb_evfinalize = 0x425920 <rspamd_term_handler>, evcb_cbfinalize = 0x425920 <rspamd_term_handler>},
    evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7fffffffffff, tqe_prev = 0x7fffffffead0}, min_heap_idx = -1}, ev_fd = 15, ev_base = 0x8086f3d00, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x80869bb88}, ev_timeout = {tv_sec = 140737488289792, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x80869bb88}, ev_ncalls = 0,
      ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 0, tv_usec = 34369544192}}
        int_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x804411808, tqe_prev = 0x805416000}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x425920 <rspamd_term_handler>, evcb_selfcb = 0x425920 <rspamd_term_handler>, evcb_evfinalize = 0x425920 <rspamd_term_handler>, evcb_cbfinalize = 0x425920 <rspamd_term_handler>},
    evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7fffffffffff, tqe_prev = 0x803b2a7cc}, min_heap_idx = -1}, ev_fd = 2, ev_base = 0x8086f3d00, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x80869bbb0}, ev_timeout = {tv_sec = 34432286720, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x80869bbb0}, ev_ncalls = 0,
      ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 34369544192, tv_usec = 140737488349904}}
        cld_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x0, tqe_prev = 0x809305650}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x425a80 <rspamd_cld_handler>, evcb_selfcb = 0x425a80 <rspamd_cld_handler>, evcb_evfinalize = 0x425a80 <rspamd_cld_handler>, evcb_cbfinalize = 0x425a80 <rspamd_cld_handler>},
    evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x80095c030}, min_heap_idx = -1}, ev_fd = 20, ev_base = 0x8086f3d00, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x80869bbc0}, ev_timeout = {tv_sec = 109707264, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x80869bbc0}, ev_ncalls = 0,
      ev_pncalls = 0x0}}, ev_events = 24, ev_res = 8, ev_timeout = {tv_sec = 1, tv_usec = 34369544192}}
        hup_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x0, tqe_prev = 0x809305650}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x4259c0 <rspamd_hup_handler>, evcb_selfcb = 0x4259c0 <rspamd_hup_handler>, evcb_evfinalize = 0x4259c0 <rspamd_hup_handler>, evcb_cbfinalize = 0x4259c0 <rspamd_hup_handler>},
    evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x68acf04}, min_heap_idx = -1}, ev_fd = 1, ev_base = 0x8086f3d00, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x80869bbb8}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x80869bbb8}, ev_ncalls = 0, ev_pncalls = 0x0}},
  ev_events = 24, ev_res = 8, ev_timeout = {tv_sec = 0, tv_usec = 140737488349120}}
        usr1_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x800958400, tqe_prev = 0x800958800}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 1 '\001', evcb_cb_union = {
      evcb_callback = 0x426000 <rspamd_usr1_handler>, evcb_selfcb = 0x426000 <rspamd_usr1_handler>, evcb_evfinalize = 0x426000 <rspamd_usr1_handler>, evcb_cbfinalize = 0x426000 <rspamd_usr1_handler>},
    evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x8ffffffff, tqe_prev = 0x800959c00}, min_heap_idx = -1}, ev_fd = 30, ev_base = 0x8086f3d00, ev_ = {ev_io = {
      ev_io_next = {le_next = 0x0, le_prev = 0x80869bbc8}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0, le_prev = 0x80869bbc8}, ev_ncalls = 0, ev_pncalls = 0x0}},
  ev_events = 24, ev_res = 0, ev_timeout = {tv_sec = 0, tv_usec = 0}}
        control_ev = {ev_evcallback = {evcb_active_next = {tqe_next = 0x7fffffffe978, tqe_prev = 0x7fffffffe960}, evcb_flags = 128, evcb_pri = 0 '\0', evcb_closure = 2 '\002', evcb_cb_union = {
      evcb_callback = 0x426a00 <rspamd_control_handler>, evcb_selfcb = 0x426a00 <rspamd_control_handler>, evcb_evfinalize = 0x426a00 <rspamd_control_handler>,
      evcb_cbfinalize = 0x426a00 <rspamd_control_handler>}, evcb_arg = 0x805433000}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x8ffffffff, tqe_prev = 0x800950c00}, min_heap_idx = -1},
  ev_fd = 5, ev_base = 0x8086f3d00, ev_ = {ev_io = {ev_io_next = {le_next = 0x0, le_prev = 0x808729460}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {le_next = 0x0,
        le_prev = 0x808729460}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 18, ev_res = 0, ev_timeout = {tv_sec = 34369534976, tv_usec = 34369536000}}
        term_tv = {tv_sec = 217, tv_usec = 34369503232}
        rspamd_main = (struct rspamd_main *) 0x805433000
        skip_pid = 0
        valgrind_mode = 0
(gdb) q
```

**Comment by sschimi** [comment]
Ahh, you're right. Selecting the individual server fixes the problem, having the same segfault issue turning into a bad gateway afterwards.

is it correct, that one item is last over? the others are deleted correctly

**Comment by moisseev** [comment]
Yes, you are absolutely right, all entries were deleted except one.
Sorry, I should have been more specific.

**Comment by moisseev** [comment]
@vstakhov The outstanding issue is that the last entry is always left after history reset.

**Comment by moisseev** [comment]
@vstakhov The last entry is still left after history reset.
