### ISSUE TITLE
abort due to invalid pointer

### ISSUE THREAD

**Issue by philfry** [rspamd/rspamd#2448]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [X] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.9

### Operation system, CPU:
CentOS 7, Intel i7

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
```
*** Error in `rspamd: controller process (192.168.255.1:11334)': munmap_chunk(): invalid pointer: 0x0000000041379378 ***
```

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
```
#0  0x00007f83636ae277 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f83636af968 in __GI_abort () at abort.c:90
#2  0x00007f83636f0d37 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f8363802d58 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#3  0x00007f83636f75e4 in malloc_printerr (action=<optimized out>, str=0x7f8363802d80 "munmap_chunk(): invalid pointer", ptr=<optimized out>, 
    ar_ptr=<optimized out>) at malloc.c:5025
#4  0x000000000046bf69 in kh_destroy_rspamd_map_hash (h=0x2277370) at /usr/src/debug/rspamd-1.7.9/src/libutil/map_helpers.c:43
#5  rspamd_map_helper_destroy_hash (r=0x2e4f020) at /usr/src/debug/rspamd-1.7.9/src/libutil/map_helpers.c:632
#6  0x00000000004691f2 in rspamd_map_remove_all (cfg=cfg@entry=0x2d11be0) at /usr/src/debug/rspamd-1.7.9/src/libutil/map.c:2063
#7  0x00000000004add0c in rspamd_config_free (cfg=0x2d11be0) at /usr/src/debug/rspamd-1.7.9/src/libserver/cfg_utils.c:214
#8  0x0000000000431be3 in start_controller_worker (worker=0x34ee1c0) at /usr/src/debug/rspamd-1.7.9/src/controller.c:3870
#9  0x00000000004df9df in rspamd_fork_worker (rspamd_main=rspamd_main@entry=0x1ae8100, cf=cf@entry=0x1f97070, index=index@entry=0, 
    ev_base=ev_base@entry=0x2cb57f0) at /usr/src/debug/rspamd-1.7.9/src/libserver/worker_util.c:685
#10 0x00000000004399eb in spawn_worker_type (rspamd_main=rspamd_main@entry=0x1ae8100, ev_base=ev_base@entry=0x2cb57f0, cf=cf@entry=0x1f97070)
    at /usr/src/debug/rspamd-1.7.9/src/rspamd.c:535
#11 0x000000000043a71d in spawn_workers (rspamd_main=0x1ae8100, ev_base=0x2cb57f0) at /usr/src/debug/rspamd-1.7.9/src/rspamd.c:628
#12 0x00007f836772bd3b in event_signal_closure (base=<optimized out>, base=<optimized out>, ev=0x7fff3527ef70) at event.c:1064
#13 event_process_active_single_queue (activeq=0x2c2b940, base=0x2cb57f0) at event.c:1342
#14 event_process_active (base=<optimized out>) at event.c:1420
#15 event_base_loop (base=base@entry=0x2cb57f0, flags=flags@entry=0) at event.c:1621
#16 0x000000000042c7d8 in main (argc=1, argv=0x7fff3527f378, env=<optimized out>) at /usr/src/debug/rspamd-1.7.9/src/rspamd.c:1473
```

### Configuration (e.g. `rspamadm configdump module`):
```
*** Section worker ***
fuzzy {
    backend = "redis";
    database = 2;
    allow_update [
        "127.0.0.1",
        "::1",
    ]
    expire = 7776000;
    count = 4;
    bind_socket = "localhost:11335";
    sync = 60;
}

*** End of section worker ***
*** Section worker ***
normal {
    task_timeout = 8;
    enabled = false;
    bind_socket = "localhost:11333";
    mime = true;
}

*** End of section worker ***
*** Section worker ***
controller {
    password = "...";
    secure_ip = "127.0.0.1";
    secure_ip = "::1";
    enable_password = "...";
    static_dir = "/usr/share/rspamd/www";
    count = 1;
    bind_socket = "localhost:11334";
    bind_socket = "192.168.255.1:11334";
}

*** End of section worker ***
*** Section worker ***
rspamd_proxy {
    max_retries = 5;
    client_ca_name = "my CA";
    timeout = 120;
    spam_header = "X-Spam";
    quarantine_on_reject = false;
    reject_message = "Spam message rejected";
    discard_on_reject = false;
    milter = true;
    upstream {
        local {
            hosts = "localhost";
            self_scan = true;
            default = true;
        }
    }
    bind_socket = "/run/rspamd/milter.socket mode=0660 owner=_rspamd group=mail";
    count = 1;
}

*** End of section worker ***
*** Section worker ***
fuzzy {
    backend = "redis";
    allow_update [
        "localhost",
    ]
    count = -1;
    bind_socket = "localhost:11335";
    expire = 7776000;
}

*** End of section worker ***
```

**Comment by philfry** [comment]
```
2018-09-17 07:26:28 #12345(controller) <hntukx>; map; http_map_finish: https://maps.rspamd.com/rspamd/mime_types.inc.zst(212.24.145.107:443): read map data 9612 bytes compressed, 480
61 uncompressed, next check at Mon, 17 Sep 2018 09:26:28 GMT
2018-09-17 07:26:28 #12345(controller) <hntukx>; map; rspamd_map_save_http_cached_file: saved data from https://maps.rspamd.com/rspamd/mime_types.inc.zst in /var/lib/rspamd/2e66b2415
ec9b99aaa155761c211e51def12016e.map, 48061 bytes
2018-09-17 07:26:28 #12345(controller) <hntukx>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/mime_types.inc.local
2018-09-17 07:26:28 #12345(controller) <hntukx>; map; read_map_file: /var/lib/rspamd/mime_types.inc.local: map file is not found; it will be read automatically if created
2018-09-17 07:26:28 #12345(controller) rspamd_crash_sig_handler: caught fatal signal 6(Aborted), pid: 12345, trace: 
2018-09-17 07:26:28 #2697(main) <b2aa07>; main; rspamd_cld_handler: catch SIGCHLD signal, finding terminated workers
2018-09-17 07:26:28 #2697(main) <b2aa07>; main; rspamd_cld_handler: controller process 12345 terminated abnormally by signal: Aborted and created core file
```

```
#0  0x00007f83636ae277 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 12345
        selftid = 12345
#1  0x00007f83636af968 in __GI_abort () at abort.c:90
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7fff3527da9a, sa_sigaction = 0x7fff3527da9a}, sa_mask = {__val = {6, 140202286782889, 2, 140734085192366, 2, 140202286774151, 1, 140202286782885, 3, 140734085192340, 12, 140202286782889, 2, 140734085193152, 140734085193152, 140734085194912}}, sa_flags = 19, sa_restorer = 0x7fff3527dfc0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f83636f0d37 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f8363802d58 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
        ap = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fff3527e4b0, reg_save_area = 0x7fff3527e3c0}}
        ap_copy = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fff3527e4b0, reg_save_area = 0x7fff3527e3c0}}
        fd = 2
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007f83636f75e4 in malloc_printerr (action=<optimized out>, str=0x7f8363802d80 "munmap_chunk(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5025
        buf = "0000000040328378"
        cp = <optimized out>
        ar_ptr = <optimized out>
        ptr = <optimized out>
        str = 0x7f8363802d80 "munmap_chunk(): invalid pointer"
        action = <optimized out>
#4  0x000000000046bf69 in kh_destroy_rspamd_map_hash (h=0x33fbb70) at /usr/src/debug/rspamd-1.7.9/src/libutil/map_helpers.c:43
No locals.
#5  rspamd_map_helper_destroy_hash (r=0x2dd7eb0) at /usr/src/debug/rspamd-1.7.9/src/libutil/map_helpers.c:632
No locals.
#6  0x000000000046c268 in rspamd_kv_list_fin (data=0x200df88) at /usr/src/debug/rspamd-1.7.9/src/libutil/map_helpers.c:804
        map = 0x4fab670
        htb = <optimized out>
        __func__ = "rspamd_kv_list_fin"
#7  0x0000000000465602 in rspamd_map_periodic_dtor (periodic=0x200df80) at /usr/src/debug/rspamd-1.7.9/src/libutil/map.c:1143
        map = <optimized out>
        __func__ = "rspamd_map_periodic_dtor"
#8  0x0000000000465d90 in free_http_cbdata_common (plan_new=1, cbd=<optimized out>) at /usr/src/debug/rspamd-1.7.9/src/libutil/map.c:283
        periodic = 0x200df80
#9  free_http_cbdata (cbd=0x1b4fbd0) at /usr/src/debug/rspamd-1.7.9/src/libutil/map.c:293
No locals.
#10 0x0000000000467596 in http_map_finish (conn=<optimized out>, msg=<optimized out>) at /usr/src/debug/rspamd-1.7.9/src/libutil/map.c:835
        cbd = 0x1b4fbd0
        map = 0x4fab670
        bk = <optimized out>
        data = <optimized out>
        cache_cbd = <optimized out>
        tv = {tv_sec = -1537161388, tv_usec = 0}
        expires_hdr = <optimized out>
        etag_hdr = <optimized out>
        next_check_date = "Mon, 17 Sep 2018 09:26:28 GMT\000)\322@DN\003\000\000\000\000`\304\002\004", '\000' <repeats 20 times>, "\260\324c\000\000\000\000\000\312\371sg\203\177\000\000\064\000\000\000\002\000\002\000\000|K\v\\\351)\322/dev/shm\267\250sg\203\177\000\000\065\064\063\063e190@DN\003\000\000\000"
        aux_data = <optimized out>
        in = <optimized out>
        inlen = 0
        dlen = 9612
        __func__ = "http_map_finish"
#11 0x000000000045f367 in rspamd_http_on_message_complete (parser=<optimized out>) at /usr/src/debug/rspamd-1.7.9/src/libutil/http.c:957
        conn = 0x1b38220
        priv = 0x34e43b0
        ret = <optimized out>
        mode = <optimized out>
        __func__ = "rspamd_http_on_message_complete"
#12 0x000000000057ff4d in http_parser_execute (parser=parser@entry=0x34e43e0, settings=settings@entry=0x34e4400, data=<optimized out>, len=len@entry=1740) at /usr/src/debug/rspamd-1.7.9/contrib/http-parser/http_parser.c:1772
        c = <optimized out>
        ch = 117 'u'
        unhex_val = <optimized out>
        p = 0x29e137b "\320\367:/c \345\215W\267\031)\207\277\032%\\\275\210\362JG)Q\243\331f\265\373\371jql\244`\220\247rP4p\003s\347\v3y\032\327J\266*y\200A\202\006\204\210wy^qabj\353\370+I6ۥ]\231p\235K\335\376C\205\250\210\065,\"5!\320:r\031\356\333w\222\303\321\t\245\221\221\365\367\355\324@]\205\377\277\241,xJV*<DLH@D\005\207\033\033\246\370躣B\250,\213m\374\344\337\313\330y\034uy\207b\212\062\345\030\265\373\275\177hA\033\237\257\230R\241\362\272\354\235\035dvy\245\274\200\210ubo\211s\342 Z8b&\220\362mxP%\273\315\372d\235W"...
        header_field_mark = <optimized out>
        header_value_mark = <optimized out>
        url_mark = <optimized out>
        body_mark = <optimized out>
        status_mark = <optimized out>
        __PRETTY_FUNCTION__ = "http_parser_execute"
#13 0x0000000000460e31 in rspamd_http_event_handler (fd=<optimized out>, what=<optimized out>, ud=0x1b38220) at /usr/src/debug/rspamd-1.7.9/src/libutil/http.c:1174
        conn = 0x1b38220
        priv = 0x34e43b0
        pbuf = 0x3678d70
        d = 0x29e0cb0 "u\327\276l\375\030\177xikfE\203ӹ\330C\364\371\375\215\327\063\063\002\v$M\300\005[\n'{\303\b\275a\221\271\061\071\066\330$\340\235\361yWi\203\303V"
        r = 1740
        err = <optimized out>
        __func__ = "rspamd_http_event_handler"
#14 0x00007f836772ba14 in event_process_active_single_queue (activeq=0x2cb6120, base=0x28ad880) at event.c:1350
        ev = 0x34e4440
        count = 1
#15 event_process_active (base=<optimized out>) at event.c:1420
        activeq = 0x2cb6120
        i = 0
        c = 0
#16 event_base_loop (base=0x28ad880, flags=flags@entry=0) at event.c:1621
        evsel = 0x7f8367960be0 <epollops>
        tv = {tv_sec = 0, tv_usec = 320461}
        tv_p = <optimized out>
        res = <optimized out>
        done = 0
        retval = 0
        __func__ = "event_base_loop"
#17 0x0000000000431b71 in start_controller_worker (worker=0x2d49220) at /usr/src/debug/rspamd-1.7.9/src/controller.c:3851
        ctx = 0x44c1700
        mctx = <optimized out>
        iter = {dummy1 = 0x1b80000, dummy2 = 0x5eb0be, dummy3 = 0x10, dummy4 = 8, dummy5 = 32767, dummy6 = 0x7fff00000003}
        key = 0x607f7c
        value = 0x2783e60
        i = <optimized out>
        cache = <optimized out>
        stv = {tv_sec = 60, tv_usec = 0}
        m = <optimized out>
        __func__ = "start_controller_worker"
#18 0x00000000004df9df in rspamd_fork_worker (rspamd_main=rspamd_main@entry=0x1ae8100, cf=cf@entry=0x2be3080, index=index@entry=0, ev_base=ev_base@entry=0x2cb57f0) at /usr/src/debug/rspamd-1.7.9/src/libserver/worker_util.c:685
        wrk = 0x2d49220
        rc = <optimized out>
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
        __func__ = "rspamd_fork_worker"
#19 0x00000000004399eb in spawn_worker_type (rspamd_main=rspamd_main@entry=0x1ae8100, ev_base=ev_base@entry=0x2cb57f0, cf=cf@entry=0x2be3080) at /usr/src/debug/rspamd-1.7.9/src/rspamd.c:535
        i = 0
        __func__ = "spawn_worker_type"
#20 0x000000000043a71d in spawn_workers (rspamd_main=0x1ae8100, ev_base=0x2cb57f0) at /usr/src/debug/rspamd-1.7.9/src/rspamd.c:628
        cur = <optimized out>
        ls = <optimized out>
        cf = <optimized out>
        p = <optimized out>
        bcf = <optimized out>
        listen_ok = <optimized out>
        seen_mandatory_workers = 0x1b3da80
        cw = <optimized out>
        wrk = <optimized out>
        i = <optimized out>
        __func__ = "spawn_workers"
#21 0x00007f836772bd3b in event_signal_closure (base=<optimized out>, base=<optimized out>, ev=0x7fff3527ef70) at event.c:1064
        ncalls = 0
        should_break = <optimized out>
#22 event_process_active_single_queue (activeq=0x2c2b940, base=0x2cb57f0) at event.c:1342
        ev = 0x7fff3527ef70
        count = 1
#23 event_process_active (base=<optimized out>) at event.c:1420
        activeq = 0x2c2b940
        i = 0
        c = 0
#24 event_base_loop (base=base@entry=0x2cb57f0, flags=flags@entry=0) at event.c:1621
        evsel = 0x7f8367960be0 <epollops>
        tv = {tv_sec = 0, tv_usec = 499904}
        tv_p = <optimized out>
        res = <optimized out>
        done = 0
        retval = 0
        __func__ = "event_base_loop"
#25 0x000000000042c7d8 in main (argc=1, argv=0x7fff3527f378, env=<optimized out>) at /usr/src/debug/rspamd-1.7.9/src/rspamd.c:1473
        i = <optimized out>
        res = 0
        signals = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        sigpipe_act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {4096, 0 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0x1e}
        pworker = <optimized out>
        type = <optimized out>
        control_addr = 0x2cb56e0
        ev_base = 0x2cb57f0
        term_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_next = {tqe_next = 0x7fff3527ee50, tqe_prev = 0x2cb5950}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x7fff3527f3a0}, min_heap_idx = -1}, ev_fd = 15, ev_base = 0x2cb57f0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x2cb6120}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x2cb6120}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 140734085198752, tv_usec = 140734085198712}, ev_callback = 0x439a40 <rspamd_term_handler>, ev_arg = 0x1ae8100}
        int_ev = {ev_active_next = {tqe_next = 0x1, tqe_prev = 0x0}, ev_next = {tqe_next = 0x7fff3527ef70, tqe_prev = 0x2cb5950}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x706374ffffffff, tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 2, ev_base = 0x2cb57f0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x2cb6280}, ev_timeout = {tv_sec = 5177800049796251648, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x2cb6280}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = -6311234926996614446, tv_usec = 7812991749446479684}, ev_callback = 0x439a40 <rspamd_term_handler>, ev_arg = 0x1ae8100}
        cld_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x2c2b940}, ev_next = {tqe_next = 0x7fff3527f000, tqe_prev = 0x2cb5950}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xe5c977ecffffffff, tqe_prev = 0x2b738a05b80c642a}, min_heap_idx = -1}, ev_fd = 17, ev_base = 0x2cb57f0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x2cb6060}, ev_timeout = {tv_sec = 2229627213051396096, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x2cb6060}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 8, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 3440743454355002240, tv_usec = -2954958152259328523}, ev_callback = 0x439d30 <rspamd_cld_handler>, ev_arg = 0x1ae8100}
        hup_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x2c2b940}, ev_next = {tqe_next = 0x7fff3527eee0, tqe_prev = 0x2cb5950}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 1, ev_base = 0x2cb57f0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x2cb5fa0}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x2cb5fa0}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 8, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 0, tv_usec = 0}, ev_callback = 0x43ad30 <rspamd_hup_handler>, ev_arg = 0x1ae8100}
        usr1_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_next = {tqe_next = 0x7fff3527f090, tqe_prev = 0x2cb5950}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 10, ev_base = 0x2cb57f0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x29b06a0}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x29b06a0}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 0, tv_usec = 0}, ev_callback = 0x4398d0 <rspamd_usr1_handler>, ev_arg = 0x1ae8100}
        control_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_next = {tqe_next = 0x2d49e68, tqe_prev = 0x2cb5950}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 4, ev_base = 0x2cb57f0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x28abd30}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x28abd30}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 18, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 2 '\002', ev_timeout = {tv_sec = 0, tv_usec = -140734085198207}, ev_callback = 0x439800 <rspamd_control_handler>, ev_arg = 0x1ae8100}
        term_tv = {tv_sec = 31, tv_usec = 140202365337600}
        skip_pid = 1
        valgrind_mode = <optimized out>
        __func__ = "main"
```
