### ISSUE TITLE
rspamd controller process segfaulted in min_heap_elem_greater

### ISSUE THREAD

**Issue by philfry** [rspamd/rspamd#2569]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [X] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.0

### Operation system, CPU:
CentOS 7, Intel i7

### Description (Please provide a descriptive summary of the issue):
Happened after reloading rspamd

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
```
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: catch SIGCHLD signal, finding terminated workers
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: controller process 26753 terminated abnormally by signal: Segmentation fault and created core file
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: catch SIGCHLD signal, finding terminated workers
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: fuzzy process 26755 terminated normally
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: catch SIGCHLD signal, finding terminated workers
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: fuzzy process 26757 terminated normally
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: catch SIGCHLD signal, finding terminated workers
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: fuzzy process 26756 terminated normally
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: catch SIGCHLD signal, finding terminated workers
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: rspamd_proxy process 26752 terminated normally
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: catch SIGCHLD signal, finding terminated workers
2018-10-05 04:05:14 #26748(main) <56bad7>; main; rspamd_cld_handler: fuzzy process 26754 terminated normally
```

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
```
#0  min_heap_elem_greater (a=0x7fadf2de3a48, a=0x7fadf2de3a48, b=0x1b9cbb8, b=0x1b9cbb8) at minheap-internal.h:61
#1  min_heap_erase (e=0x1b5c4b0, s=0x1b5c630) at minheap-internal.h:107
        last = 0x1b9cbb8
        parent = 1
#2  event_queue_remove (base=base@entry=0x1b5c4b0, ev=ev@entry=0x9c34d0, queue=queue@entry=1) at event.c:2533
        __func__ = "event_queue_remove"
#3  0x00007fadf8b51342 in event_del_internal (ev=<optimized out>) at event.c:2242
        base = 0x1b5c4b0
        res = <optimized out>
        notify = <optimized out>
#4  event_del (ev=0x9c34d0) at event.c:2188
No locals.
#5  0x00000000004d4334 in rspamd_monitored_ctx_destroy (ctx=0x9c6160) at /usr/src/debug/rspamd-1.8.0/src/libserver/monitored.c:628
        m = 0x9c3460
        i = 7
        __func__ = "rspamd_monitored_ctx_destroy"
#6  0x00000000004b1785 in rspamd_config_free (cfg=0x9c2c00) at /usr/src/debug/rspamd-1.8.0/src/libserver/cfg_utils.c:263
        sc = <optimized out>
        sctmp = <optimized out>
        lp = <optimized out>
        ltmp = <optimized out>
#7  0x00000000004327a6 in start_controller_worker (worker=0x1b5d310) at /usr/src/debug/rspamd-1.8.0/src/controller.c:3871
        ctx = 0x7fadf2de3960
        mctx = <optimized out>
        iter = {dummy1 = 0x16d44c0, dummy2 = 0x5f6f42, dummy3 = 0x10, dummy4 = 8, dummy5 = 32764, dummy6 = 0x7ffc00000003}
        key = 0x619308
        value = 0x1b96430
        i = <optimized out>
        cache = <optimized out>
        stv = {tv_sec = 60, tv_usec = 0}
        m = <optimized out>
        __func__ = "start_controller_worker"
#8  0x00000000004e9b21 in rspamd_fork_worker (rspamd_main=rspamd_main@entry=0x9c1100, cf=cf@entry=0xa573f0, index=index@entry=0, ev_base=ev_base@entry=0x1b5c4b0) at /usr/src/debug/rspamd-1.8.0/src/libserver/worker_util.c:687
        wrk = 0x1b5d310
        rc = <optimized out>
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
        __func__ = "rspamd_fork_worker"
#9  0x000000000043a5bb in spawn_worker_type (rspamd_main=rspamd_main@entry=0x9c1100, ev_base=ev_base@entry=0x1b5c4b0, cf=cf@entry=0xa573f0) at /usr/src/debug/rspamd-1.8.0/src/rspamd.c:536
        i = 0
        __func__ = "spawn_worker_type"
#10 0x000000000043b2ed in spawn_workers (rspamd_main=rspamd_main@entry=0x9c1100, ev_base=ev_base@entry=0x1b5c4b0) at /usr/src/debug/rspamd-1.8.0/src/rspamd.c:629
        cur = <optimized out>
        ls = <optimized out>
        cf = <optimized out>
        p = <optimized out>
        bcf = <optimized out>
        listen_ok = <optimized out>
        seen_mandatory_workers = 0x1b53ec0
        cw = <optimized out>
        wrk = <optimized out>
        i = <optimized out>
        __func__ = "spawn_workers"
#11 0x000000000042d313 in main (argc=1, argv=0x7ffc7a9adbf8, env=<optimized out>) at /usr/src/debug/rspamd-1.8.0/src/rspamd.c:1463
        i = <optimized out>
        res = 0
        signals = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        sigpipe_act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {4096, 0 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0x1e}
        pworker = <optimized out>
        type = <optimized out>
        control_addr = 0x1b62bd0
        ev_base = 0x1b5c4b0
        term_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_next = {tqe_next = 0x7ffc7a9ad6d0, tqe_prev = 0x1b5c610}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x7ffc7a9adc20}, min_heap_idx = -1}, ev_fd = 15, ev_base = 0x1b5c4b0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x1b5cde0}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x1b5cde0}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 140722365455392, tv_usec = 140722365455352}, ev_callback = 0x43a610 <rspamd_term_handler>, ev_arg = 0x9c1100}
        int_ev = {ev_active_next = {tqe_next = 0x1, tqe_prev = 0x0}, ev_next = {tqe_next = 0x7ffc7a9ad7f0, tqe_prev = 0x1b5c610}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x706374ffffffff, tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 2, ev_base = 0x1b5c4b0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x1b5cf40}, ev_timeout = {tv_sec = -2069974591614353408, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x1b5cf40}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = -5722103099153058819, tv_usec = 8910082603276765844}, ev_callback = 0x43a610 <rspamd_term_handler>, ev_arg = 0x9c1100}
        cld_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_next = {tqe_next = 0x7ffc7a9ad880, tqe_prev = 0x1b5c610}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xca71fcafffffffff, tqe_prev = 0x68d2e7fa99f748d3}, min_heap_idx = -1}, ev_fd = 17, ev_base = 0x1b5c4b0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x1b5cd20}, ev_timeout = {tv_sec = -6990508278500491264, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x1b5cd20}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 1789851151278670899, tv_usec = 6510502844076822557}, ev_callback = 0x43a900 <rspamd_cld_handler>, ev_arg = 0x9c1100}
        hup_ev = {ev_active_next = {tqe_next = 0x6c6c6f72746e6f63, tqe_prev = 0x7265}, ev_next = {tqe_next = 0x7ffc7a9ad760, tqe_prev = 0x1b5c610}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x37b8c5d4ffffffff, tqe_prev = 0x31a66e70dc1add28}, min_heap_idx = -1}, ev_fd = 1, ev_base = 0x1b5c4b0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x1b5cc60}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x1b5cc60}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 0, tv_usec = 0}, ev_callback = 0x43b900 <rspamd_hup_handler>, ev_arg = 0x9c1100}
        usr1_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_next = {tqe_next = 0x1b5d108, tqe_prev = 0x1b5c610}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 10, ev_base = 0x1b5c4b0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x1b5d1b0}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x1b5d1b0}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 0, tv_usec = 0}, ev_callback = 0x43a4a0 <rspamd_usr1_handler>, ev_arg = 0x9c1100}
        control_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x0, tqe_prev = 0x0}, min_heap_idx = 0}, ev_fd = 0, ev_base = 0x0, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 0, ev_res = 0, ev_flags = 0, ev_pri = 0 '\000', ev_closure = 0 '\000', ev_timeout = {tv_sec = 0, tv_usec = -140722365454847}, ev_callback = 0x2, ev_arg = 0x0}
        term_tv = {tv_sec = 128, tv_usec = 140385193223384}
        skip_pid = 1
        valgrind_mode = <optimized out>
        __func__ = "main"
```

### Configuration (e.g. `rspamadm configdump module`):
```
*** Section worker ***
fuzzy {
    backend = "redis";
    database = 2;
    allow_update [
        "127.0.0.1",
        "::1",
    ]
    expire = 7776000;
    count = 4;
    bind_socket = "localhost:11335";
    sync = 60;
}

*** End of section worker ***
*** Section worker ***
normal {
    task_timeout = 8;
    enabled = false;
    bind_socket = "localhost:11333";
    mime = true;
}

*** End of section worker ***
*** Section worker ***
controller {
    password = "...";
    secure_ip = "127.0.0.1";
    secure_ip = "::1";
    enable_password = "...";
    static_dir = "/usr/share/rspamd/www";
    count = 1;
    bind_socket = "localhost:11334";
    bind_socket = "192.168.255.1:11334";
}

*** End of section worker ***
*** Section worker ***
rspamd_proxy {
    max_retries = 5;
    client_ca_name = "my CA";
    timeout = 120;
    spam_header = "X-Spam";
    quarantine_on_reject = false;
    reject_message = "Spam message rejected";
    discard_on_reject = false;
    milter = true;
    upstream {
        local {
            hosts = "localhost";
            self_scan = true;
            default = true;
        }
    }
    bind_socket = "/run/rspamd/milter.socket mode=0660 owner=_rspamd group=mail";
    count = 1;
}

*** End of section worker ***
*** Section worker ***
fuzzy {
    backend = "redis";
    allow_update [
        "localhost",
    ]
    count = -1;
    bind_socket = "localhost:11335";
    expire = 7776000;
}

*** End of section worker ***
```

**Comment by vstakhov** [comment]
I think it is fixed now in master.
