### ISSUE TITLE
Core Dump: rspamd: controller process (localhost:11334)

### ISSUE THREAD

**Issue by tleuxner** [rspamd/rspamd#2727]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [X] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.3

### Operation system, CPU:
Debian Stretch, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz

### Description (Please provide a descriptive summary of the issue):
Controller process crashed after running running for weeks.

### Relevant logs
```
Jan 21 16:32:35 edi rspamd[9810]: <9zc4wc>; map; http_map_finish: https://maps.rspamd.com/rspamd/mid.inc.zst(212.24.145.107:443): read map data 377 bytes compressed, 602 uncompressed, next check at Mon, 21 Jan 2019 19:32:38 GMT
Jan 21 16:32:35 edi rspamd[9810]: <9zc4wc>; map; rspamd_map_save_http_cached_file: saved data from https://maps.rspamd.com/rspamd/mid.inc.zst in /var/lib/rspamd/cb5a8189726ac3a8880e1c44ed6220c6d794521b.map, 602 bytes
Jan 21 16:32:35 edi rspamd[9810]: <9zc4wc>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/local.d/mid.inc
Jan 21 16:32:35 edi rspamd[9810]: <9zc4wc>; map; read_map_file: /etc/rspamd/local.d/mid.inc: map file is not found; it will be read automatically if created
Jan 21 16:32:35 edi rspamd[9770]: <d99027>; main; rspamd_cld_handler: catch SIGCHLD signal, finding terminated workers
Jan 21 16:32:35 edi rspamd[9770]: <d99027>; main; rspamd_cld_handler: controller process 9810 terminated abnormally by signal: Bus error and created core file
Jan 21 16:32:37 edi rspamd[6363]: <d99027>; main; rspamd_fork_worker: starting controller process 6363 (0); listen on: localhost:11334
```

### Debugging information
```
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/rspamd...Reading symbols from /usr/lib/debug/.build-id/5f/20bdac35679dd02e7d851afcb3104d339345c4.debug...done.
done.
[New LWP 9810]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `rspamd: controller process (localhost:11334) '.
Program terminated with signal SIGBUS, Bus error.
#0  0x0000561350588457 in kh_destroy_rspamd_map_hash (h=0x3783f814fffe54d8) at ./src/libutil/map_helpers.c:43
43      ./src/libutil/map_helpers.c: No such file or directory.
#0  0x0000561350588457 in kh_destroy_rspamd_map_hash (h=0x3783f814fffe54d8) at ./src/libutil/map_helpers.c:43
No locals.
#1  rspamd_map_helper_destroy_hash (r=0x7f5989f26120) at ./src/libutil/map_helpers.c:645
No locals.
#2  0x000056135058b328 in rspamd_kv_list_fin (data=0x7f5987cb85c8) at ./src/libutil/map_helpers.c:817
        map = 0x7f59b6b95418
        htb = <optimized out>
        __func__ = "rspamd_kv_list_fin"
#3  0x000056135058a48a in rspamd_map_periodic_dtor (periodic=0x7f5987cb85c0) at ./src/libutil/map.c:1157
        map = <optimized out>
        __func__ = "rspamd_map_periodic_dtor"
#4  0x0000561350589cb0 in free_http_cbdata_common.isra.6 (cbd=<optimized out>) at ./src/libutil/map.c:297
        periodic = 0x7f5987cb85c0
#5  free_http_cbdata (cbd=0x7f5988cd8060) at ./src/libutil/map.c:307
No locals.
#6  0x00005613505938bc in http_map_finish (conn=<optimized out>, msg=<optimized out>) at ./src/libutil/map.c:849
        cbd = 0x7f5988cd8060
        map = <optimized out>
        bk = <optimized out>
        data = <optimized out>
        cache_cbd = <optimized out>
        tv = {tv_sec = -1548084158, tv_usec = 0}
        expires_hdr = <optimized out>
        etag_hdr = <optimized out>
        next_check_date = "Mon, 21 Jan 2019 19:32:38 GMT\000X\017\230\r\000\000\000\000\000\000\020\214h\252Y\177\000\000@JÉY\177", '\000' <repeats 18 times>, ":\237@\273Y\177\000\000!\000\000\000\002\000\002\000\000\223qd\254\272X\017aac421d5\025M@\273Y\177\000\000\066\000@\267Y\177\000\000\020\214h\252Y\177\000"
        aux_data = <optimized out>
        in = <optimized out>
        inlen = 0
        dlen = 377
        __func__ = "http_map_finish"
#7  0x00005613505c45d3 in rspamd_http_on_message_complete (parser=<optimized out>) at ./src/libutil/http.c:966
        conn = 0x7f59b4acca60
        priv = 0x7f59aa688b80
        ret = <optimized out>
        mode = <optimized out>
        __func__ = "rspamd_http_on_message_complete"
#8  0x00005613504383ca in http_parser_execute (parser=<optimized out>, settings=<optimized out>, data=<optimized out>, len=<optimized out>, len=<optimized out>, data=<optimized out>, settings=<optimized out>, parser=<optimized out>)
    at ./contrib/http-parser/http_parser.c:1772
        c = <optimized out>
        header_value_mark = 0x0
        ch = 40 '('
        unhex_val = <optimized out>
        p = 0x7f598440f2c7 <incomplete sequence \372>
        header_field_mark = <optimized out>
        url_mark = <optimized out>
        body_mark = <optimized out>
        status_mark = <optimized out>
        len = <optimized out>
        data = 0x7f598440f010 "HTTP/1.1 200 OK\r\nServer: nginx/1.14.1\r\nDate: Mon, 21 Jan 2019 15:32:38 GMT\r\nContent-Type: application/octet-stream\r\nContent-Length: 377\r\nLast-Modified: Mon, 30 Jul 2018 10:48:48 GMT\r\nConnection: close"...
        settings = <optimized out>
        parser = 0x7f59aa688bb0
        p = 0x7f598440f010 "HTTP/1.1 200 OK\r\nServer: nginx/1.14.1\r\nDate: Mon, 21 Jan 2019 15:32:38 GMT\r\nContent-Type: application/octet-stream\r\nContent-Length: 377\r\nLast-Modified: Mon, 30 Jul 2018 10:48:48 GMT\r\nConnection: close"...
#9  0x00005613505c4271 in rspamd_http_event_handler (fd=<optimized out>, what=<optimized out>, ud=0x7f59b4acca60) at ./src/libutil/http.c:1183
        conn = 0x7f59b4acca60
        priv = 0x7f59aa688b80
        pbuf = 0x7f598a3d4d60
        d = 0x7f598440f010 "HTTP/1.1 200 OK\r\nServer: nginx/1.14.1\r\nDate: Mon, 21 Jan 2019 15:32:38 GMT\r\nContent-Type: application/octet-stream\r\nContent-Length: 377\r\nLast-Modified: Mon, 30 Jul 2018 10:48:48 GMT\r\nConnection: close"...
        r = 696
        err = <optimized out>
        __func__ = "rspamd_http_event_handler"
#10 0x00007f59bb3f45a0 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
No symbol table info available.
#11 0x00005613505eab65 in start_controller_worker (worker=0x7f5989081a00) at ./src/controller.c:3901
        ctx = 0x7f59b6405b28
        mctx = <optimized out>
        iter = {dummy1 = 0x7f59b70485e0, dummy2 = 0x7f59bcc1e379 <__libc_fcntl+57>, dummy3 = 0x7ffe9c1febb2 <clock_gettime+434>, dummy4 = 8, dummy5 = 32766, dummy6 = 0x100000003}
        key = 0x561350caeacc
        value = 0x7f59b603a040
        i = <optimized out>
        cache = <optimized out>
        stv = {tv_sec = 60, tv_usec = 0}
        m = <optimized out>
        __func__ = "start_controller_worker"
#12 0x00005613504db0d0 in rspamd_fork_worker (rspamd_main=0x7f59b7067080, cf=0x7f59b70e0e00, index=0, ev_base=<optimized out>) at ./src/libserver/worker_util.c:688
        wrk = 0x7f5989081a00
        rc = <optimized out>
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
        __func__ = "rspamd_fork_worker"
#13 0x00005613505b7363 in spawn_worker_type (rspamd_main=0x7f59b7067080, ev_base=0x7f59b70d3580, cf=0x7f59b70e0e00) at ./src/rspamd.c:539
        i = 0
        __func__ = "spawn_worker_type"
#14 0x00005613505b763e in spawn_workers (rspamd_main=0x7f59b7067080, ev_base=0x7f59b70d3580) at ./src/rspamd.c:632
        cur = <optimized out>
        ls = <optimized out>
        cf = <optimized out>
        p = <optimized out>
        bcf = <optimized out>
        listen_ok = <optimized out>
        seen_mandatory_workers = 0x7f5988e18260
        cw = <optimized out>
        wrk = <optimized out>
        i = <optimized out>
        __func__ = "spawn_workers"
#15 0x000056135042f53a in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at ./src/rspamd.c:1485
        i = <optimized out>
        res = 0
        signals = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        sigpipe_act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {4096, 0 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0x0}
        pworker = <optimized out>
        type = <optimized out>
        control_addr = 0x7f59897bc250
        ev_base = 0x7f59b70d3580
        term_ev = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x0}, ev_next = {tqe_next = 0x7ffe9c1fa980, tqe_prev = 0x7f59b70d36e0}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x0}, 
            min_heap_idx = -1}, ev_fd = 15, ev_base = 0x7f59b70d3580, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f59897ff350}, ev_timeout = {tv_sec = 0, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, 
                tqe_prev = 0x7f59897ff350}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 0, tv_usec = 0}, 
          ev_callback = 0x5613505b6ce0 <rspamd_term_handler>, ev_arg = 0x7f59b7067080}
        int_ev = {ev_active_next = {tqe_next = 0x3dc300569f802032, tqe_prev = 0xff811e6f898901f1}, ev_next = {tqe_next = 0x7ffe9c1fa860, tqe_prev = 0x7f59b70d36e0}, ev_timeout_pos = {ev_next_with_common_timeout = {
              tqe_next = 0xfe9833cdffffffff, tqe_prev = 0x406eaa3110fdb6a2}, min_heap_idx = -1}, ev_fd = 2, ev_base = 0x7f59b70d3580, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f59897ff320}, ev_timeout = {
                tv_sec = 8169848000825982976, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f59897ff320}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', 
          ev_closure = 1 '\001', ev_timeout = {tv_sec = 0, tv_usec = 0}, ev_callback = 0x5613505b6ce0 <rspamd_term_handler>, ev_arg = 0x7f59b7067080}
        cld_ev = {ev_active_next = {tqe_next = 0xc008000000000000, tqe_prev = 0x0}, ev_next = {tqe_next = 0x7ffe9c1fa7d0, tqe_prev = 0x7f59b70d36e0}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, 
              tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 17, ev_base = 0x7f59b70d3580, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f59897ff330}, ev_timeout = {tv_sec = 3117874936907694080, tv_usec = 0}}, ev_signal = {
              ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f59897ff330}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', ev_timeout = {tv_sec = 0, 
            tv_usec = 5710209295282725188}, ev_callback = 0x5613505b6d40 <rspamd_cld_handler>, ev_arg = 0x7f59b7067080}
        hup_ev = {ev_active_next = {tqe_next = 0x4f3ebd199e75e144, tqe_prev = 0xfb79d8147c6764ea}, ev_next = {tqe_next = 0x7ffe9c1fa8f0, tqe_prev = 0x7f59b70d36e0}, ev_timeout_pos = {ev_next_with_common_timeout = {
              tqe_next = 0x3dc30056ffffffff, tqe_prev = 0xff811e6f898901f1}, min_heap_idx = -1}, ev_fd = 1, ev_base = 0x7f59b70d3580, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f59897ff360}, ev_timeout = {
                tv_sec = -4481253613095354368, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f59897ff360}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', 
          ev_closure = 1 '\001', ev_timeout = {tv_sec = -4686389053821884677, tv_usec = 8169848000826017022}, ev_callback = 0x5613505b7c70 <rspamd_hup_handler>, ev_arg = 0x7f59b7067080}
        usr1_ev = {ev_active_next = {tqe_next = 0x1, tqe_prev = 0x0}, ev_next = {tqe_next = 0x7f5989081928, tqe_prev = 0x7f59b70d36e0}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x7ffeffffffff, 
              tqe_prev = 0x7f59bd07829a <_dl_runtime_resolve_xsave+138>}, min_heap_idx = -1}, ev_fd = 10, ev_base = 0x7f59b70d3580, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f59897ff340}, ev_timeout = {tv_sec = 0, 
                tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f59897ff340}, ev_ncalls = 0, ev_pncalls = 0x0}}, ev_events = 24, ev_res = 0, ev_flags = 128, ev_pri = 0 '\000', ev_closure = 1 '\001', 
          ev_timeout = {tv_sec = -7433512623740776987, tv_usec = 3117874936907716517}, ev_callback = 0x5613505b7170 <rspamd_usr1_handler>, ev_arg = 0x7f59b7067080}
        control_ev = {ev_active_next = {tqe_next = 0x2, tqe_prev = 0x0}, ev_next = {tqe_next = 0x0, tqe_prev = 0xffff00001f80}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0x561350fea770, tqe_prev = 0x7ffe9c1fad20}, 
            min_heap_idx = 1358866288}, ev_fd = -1675645704, ev_base = 0x4, _ev = {ev_io = {ev_io_next = {tqe_next = 0x4, tqe_prev = 0x7f59bd070c54 <_dl_fixup+212>}, ev_timeout = {tv_sec = 1, tv_usec = 94640963467928}}, ev_signal = {
              ev_signal_next = {tqe_next = 0x4, tqe_prev = 0x7f59bd070c54 <_dl_fixup+212>}, ev_ncalls = 1, ev_pncalls = 0x561351023a98}}, ev_events = -22672, ev_res = 20734, ev_flags = 22035, ev_pri = 0 '\000', ev_closure = 0 '\000', 
          ev_timeout = {tv_sec = 140731517742368, tv_usec = 140731517742328}, ev_callback = 0x4, ev_arg = 0x7ffe9c1fabd0}
        term_tv = {tv_sec = 140023390218648, tv_usec = 140023402349624}
        skip_pid = 1
        valgrind_mode = 0
        __func__ = "main"
```

**Comment by vstakhov** [comment]
This should be fixed in the master branch.

**Comment by tleuxner** [comment]
Thanks. It messed up the learned messages. While I do have redis backups would this be good a idea to restore them? What additional steps would be required?
