### ISSUE TITLE
rspamd всё так же падает (rspamd-1.9.4-2.git9bd929050)

### ISSUE THREAD

**Issue by poralix** [rspamd/rspamd#2904]
Всеволод, доброго дня!

Поясните, пожалуйста, вы закрыли [баг-репорт](https://github.com/rspamd/rspamd/issues/2885) из-за недостаточностью информации? Или по какой другой причине?

rspamd всё так же падает и после обновления до rspamd-1.9.4-2.git9bd929050. 

С Уважением,
Алексей.

**Comment by poralix** [comment]
Backtrace:

```
Core was generated by `rspamd: controller process (localhost:11334) '.
Program terminated with signal 11, Segmentation fault.
#0  x86_64_fallback_frame_state (context=0x7ffc02d77ab0, context=0x7ffc02d77ab0, fs=0x7ffc02d77ba0) at ./md-unwind-support.h:58
58        if (*(unsigned char *)(pc+0) == 0x48
(gdb) frame 0
#0  x86_64_fallback_frame_state (context=0x7ffc02d77ab0, context=0x7ffc02d77ab0, fs=0x7ffc02d77ba0) at ./md-unwind-support.h:58
58        if (*(unsigned char *)(pc+0) == 0x48
(gdb) bt
#0  x86_64_fallback_frame_state (context=0x7ffc02d77ab0, context=0x7ffc02d77ab0, fs=0x7ffc02d77ba0) at ./md-unwind-support.h:58
#1  uw_frame_state_for (context=context@entry=0x7ffc02d77ab0, fs=fs@entry=0x7ffc02d77ba0) at ../../../libgcc/unwind-dw2.c:1253
#2  0x00007f9001b55fb9 in _Unwind_Backtrace (trace=0x7f900188cda0 <backtrace_helper>, trace_argument=0x7ffc02d77d60) at ../../../libgcc/unwind.inc:290
#3  0x00007f900188cf16 in backtrace () from /lib64/libc.so.6
#4  0x00007f90017f1d44 in __libc_message () from /lib64/libc.so.6
#5  0x00007f90018909e7 in __fortify_fail () from /lib64/libc.so.6
#6  0x00007f90018909a2 in __stack_chk_fail () from /lib64/libc.so.6
#7  0x00007f9006586646 in rspamd_vprintf_common (func=0x7f90065855b0 <rspamd_printf_append_fstring>, apd=0x7ffc02d78be0, fmt=<optimized out>, args=0x7ffc02d78760)
    at /usr/src/debug/rspamd-1.9.4/src/libutil/printf.c:1117
#8  0x3030303030303030 in ?? ()
#9  0x3030303030303030 in ?? ()
#10 0x3030303030303030 in ?? ()
#11 0x3030303030303030 in ?? ()
#12 0x3030303030303030 in ?? ()
#13 0x3030303030303030 in ?? ()
#14 0x3030303030303030 in ?? ()
#15 0x3030303030303030 in ?? ()
#16 0x3030303030303030 in ?? ()
#17 0x3030303030303030 in ?? ()
#18 0x3531303030303030 in ?? ()
#19 0x3436373635323036 in ?? ()
#20 0x0000393037323630 in ?? ()
#21 0x12168f46fb11ad34 in ?? ()
#22 0x0000000000000000 in ?? ()
(gdb) frame 0
#0  x86_64_fallback_frame_state (context=0x7ffc02d77ab0, context=0x7ffc02d77ab0, fs=0x7ffc02d77ba0) at ./md-unwind-support.h:58
58        if (*(unsigned char *)(pc+0) == 0x48
(gdb) frame 1
#1  uw_frame_state_for (context=context@entry=0x7ffc02d77ab0, fs=fs@entry=0x7ffc02d77ba0) at ../../../libgcc/unwind-dw2.c:1253
1253          return MD_FALLBACK_FRAME_STATE_FOR (context, fs);
(gdb) frame 2
#2  0x00007f9001b55fb9 in _Unwind_Backtrace (trace=0x7f900188cda0 <backtrace_helper>, trace_argument=0x7ffc02d77d60) at ../../../libgcc/unwind.inc:290
290           code = uw_frame_state_for (&context, &fs);
(gdb) frame 3
#3  0x00007f900188cf16 in backtrace () from /lib64/libc.so.6
(gdb) frame 4
#4  0x00007f90017f1d44 in __libc_message () from /lib64/libc.so.6
(gdb) frame 5
#5  0x00007f90018909e7 in __fortify_fail () from /lib64/libc.so.6
(gdb) frame 6
#6  0x00007f90018909a2 in __stack_chk_fail () from /lib64/libc.so.6
(gdb) frame 7
#7  0x00007f9006586646 in rspamd_vprintf_common (func=0x7f90065855b0 <rspamd_printf_append_fstring>, apd=0x7ffc02d78be0, fmt=<optimized out>, args=0x7ffc02d78760)
    at /usr/src/debug/rspamd-1.9.4/src/libutil/printf.c:1117
1117    }
(gdb) frame 8
#8  0x3030303030303030 in ?? ()
(gdb) frame 9
#9  0x3030303030303030 in ?? ()
(gdb)
```

**Comment by vstakhov** [comment]
Корка мне не дает ничего. Кроме того, УМВР, баг не воспроизводится.

**Comment by poralix** [comment]
Такой вариант возможно будет более информативным:

```
Core was generated by `rspamd: controller process (localhost:11334) '.
Program terminated with signal 6, Aborted.
#0  0x00007f6ff6da7207 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f6ff6da7207 in raise () from /lib64/libc.so.6
#1  0x00007f6ff6da88f8 in abort () from /lib64/libc.so.6
#2  0x00007f6ff6de9d27 in __libc_message () from /lib64/libc.so.6
#3  0x00007f6ff6e889e7 in __fortify_fail () from /lib64/libc.so.6
#4  0x00007f6ff6e889a2 in __stack_chk_fail () from /lib64/libc.so.6
#5  0x00007f6ff7c5b646 in rspamd_vprintf_common (func=func@entry=0x7f6ff7c5a5b0 <rspamd_printf_append_fstring>, apd=0x7ffeaea24fb0, fmt=<optimized out>, args=args@entry=0x7ffeaea24b30)
    at /usr/src/debug/rspamd-1.9.4/src/libutil/printf.c:1117
#6  0x00007f6ff7c5bbe5 in rspamd_vprintf_fstring (s=<optimized out>, fmt=<optimized out>, args=args@entry=0x7ffeaea24b30) at /usr/src/debug/rspamd-1.9.4/src/libutil/printf.c:569
#7  0x00007f6ff7c5bc84 in rspamd_printf_fstring (s=s@entry=0x7ffeaea24fb0, fmt=fmt@entry=0x7f6ff85169e4 "%.6f") at /usr/src/debug/rspamd-1.9.4/src/libutil/printf.c:560
#8  0x00007f6ff7c644e9 in rspamd_fstring_emit_append_double (val=-3.6817595395344857e-68, ud=ud@entry=0x7ffeaea24fb0) at /usr/src/debug/rspamd-1.9.4/src/libutil/str_util.c:2368
#9  0x0000000000484d9f in ucl_emitter_common_elt (ctx=ctx@entry=0x7ffeaea24f00, obj=<optimized out>, obj@entry=0x7f6fee2807c0, first=<optimized out>, print_key=print_key@entry=true,
    compact=compact@entry=true) at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:411
#10 0x00000000004852c9 in ucl_emitter_common_start_object (ctx=ctx@entry=0x7ffeaea24f00, obj=0x7f6fee280680, print_key=print_key@entry=false, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:342
#11 0x0000000000484e32 in ucl_emitter_common_elt (ctx=ctx@entry=0x7ffeaea24f00, obj=<optimized out>, first=<optimized out>, print_key=print_key@entry=false, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:449
#12 0x00000000004850d7 in ucl_emitter_common_start_array (ctx=ctx@entry=0x7ffeaea24f00, obj=0x7f6fee280200, print_key=print_key@entry=true, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:272
#13 0x0000000000484e62 in ucl_emitter_common_elt (ctx=ctx@entry=0x7ffeaea24f00, obj=<optimized out>, obj@entry=0x7f6fee280200, first=<optimized out>, print_key=print_key@entry=true,
    compact=compact@entry=true) at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:453
#14 0x00000000004852c9 in ucl_emitter_common_start_object (ctx=ctx@entry=0x7ffeaea24f00, obj=0x7f6fee280140, print_key=print_key@entry=false, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:342
#15 0x0000000000484e32 in ucl_emitter_common_elt (ctx=ctx@entry=0x7ffeaea24f00, obj=<optimized out>, first=<optimized out>, print_key=print_key@entry=false, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:449
#16 0x00000000004850d7 in ucl_emitter_common_start_array (ctx=ctx@entry=0x7ffeaea24f00, obj=0x7f6fed0d9ec0, print_key=print_key@entry=false, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:272
#17 0x0000000000484e62 in ucl_emitter_common_elt (ctx=0x7ffeaea24f00, obj=<optimized out>, first=<optimized out>, print_key=<optimized out>, compact=<optimized out>)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:453
#18 0x0000000000485448 in ucl_object_emit_full (obj=obj@entry=0x7f6fed0d9ec0, emit_type=emit_type@entry=UCL_EMIT_JSON_COMPACT, emitter=emitter@entry=0x7ffeaea24f60,
    comments=comments@entry=0x0) at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:681
#19 0x00007f6ff7c67da9 in rspamd_ucl_emit_fstring_comments (obj=obj@entry=0x7f6fed0d9ec0, emit_type=emit_type@entry=UCL_EMIT_JSON_COMPACT, buf=buf@entry=0x7ffeaea24fb0,
    comments=comments@entry=0x0) at /usr/src/debug/rspamd-1.9.4/src/libutil/str_util.c:2393
#20 0x00007f6ff7cf0392 in rspamd_controller_send_ucl (entry=entry@entry=0x7f6fed0de4e0, obj=obj@entry=0x7f6fed0d9ec0) at /usr/src/debug/rspamd-1.9.4/src/libserver/worker_util.c:486
#21 0x0000000000415c82 in rspamd_controller_handle_symbols (conn_ent=conn_ent@entry=0x7f6fed0de4e0, msg=msg@entry=0x7f6fece018e0) at /usr/src/debug/rspamd-1.9.4/src/controller.c:850
#22 0x00007f6ff7c4c409 in rspamd_http_router_finish_handler (conn=<optimized out>, msg=0x7f6fece018e0) at /usr/src/debug/rspamd-1.9.4/src/libutil/http_router.c:334
#23 0x00007f6ff7c4a295 in rspamd_http_on_message_complete (parser=<optimized out>) at /usr/src/debug/rspamd-1.9.4/src/libutil/http_connection.c:700
#24 0x00007f6ff7d3d800 in http_parser_execute (parser=parser@entry=0x7f6ff5aaee38, settings=settings@entry=0x7f6ff5aaee58,
    data=0x7f6fecdcf810 "GET /symbols HTTP/1.1\r\nHost: 127.0.0.1:11334\r\nUser-Agent: DirectAdmin / 1.56.4\r\nAccept: */*\r\nAccept-Encoding: deflate, gzip\r\nReferer: https://server.example.net:2222/CMD_PLUGINS_ADMIN/rspamd/\r\nX-Forwar"..., len=len@entry=222) at /usr/src/debug/rspamd-1.9.4/contrib/http-parser/http_parser.c:1717
#25 0x00007f6ff7c4aec6 in rspamd_http_event_handler (fd=<optimized out>, what=<optimized out>, ud=0x7f6fecbd5590) at /usr/src/debug/rspamd-1.9.4/src/libutil/http_connection.c:942
#26 0x00007f6ffbc23a14 in event_process_active_single_queue (activeq=0x7f6fecfbc4f0, base=0x7f6fecbd1d00) at event.c:1350
#27 event_process_active (base=<optimized out>) at event.c:1420
#28 event_base_loop (base=0x7f6fecbd1d00, flags=flags@entry=0) at event.c:1621
#29 0x000000000041695f in start_controller_worker (worker=0x7f6fecbc4380) at /usr/src/debug/rspamd-1.9.4/src/controller.c:3928
#30 0x00007f6ff7cf0b4d in rspamd_fork_worker (rspamd_main=0x7f6ff59d8000, cf=0x7f6ff5aa9380, index=0, ev_base=<optimized out>)
    at /usr/src/debug/rspamd-1.9.4/src/libserver/worker_util.c:749
#31 0x000000000041ec96 in rspamd_fork_delayed_cb (signo=<optimized out>, what=<optimized out>, arg=0x7f6fecdff7c0) at /usr/src/debug/rspamd-1.9.4/src/rspamd.c:372
#32 0x00007f6ffbc23a14 in event_process_active_single_queue (activeq=0x7f6fecfbc510, base=0x7f6fecbd1d00) at event.c:1350
#33 event_process_active (base=<optimized out>) at event.c:1420
---Type <return> to continue, or q <return> to quit---
#34 event_base_loop (base=base@entry=0x7f6fecbd1d00, flags=flags@entry=0) at event.c:1621
#35 0x00000000004117fc in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /usr/src/debug/rspamd-1.9.4/src/rspamd.c:1541
(gdb)
(gdb)
(gdb) frame 35
#35 0x00000000004117fc in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /usr/src/debug/rspamd-1.9.4/src/rspamd.c:1541
1541            event_base_loop (ev_base, 0);
(gdb) frame 1
#1  0x00007f6ff6da88f8 in abort () from /lib64/libc.so.6
(gdb) frame 2
#2  0x00007f6ff6de9d27 in __libc_message () from /lib64/libc.so.6
(gdb) frame 3
#3  0x00007f6ff6e889e7 in __fortify_fail () from /lib64/libc.so.6
(gdb) frame 4
#4  0x00007f6ff6e889a2 in __stack_chk_fail () from /lib64/libc.so.6
(gdb) frame 5
#5  0x00007f6ff7c5b646 in rspamd_vprintf_common (func=func@entry=0x7f6ff7c5a5b0 <rspamd_printf_append_fstring>, apd=0x7ffeaea24fb0, fmt=<optimized out>, args=args@entry=0x7ffeaea24b30)
    at /usr/src/debug/rspamd-1.9.4/src/libutil/printf.c:1117
1117    }
(gdb) frame 6
#6  0x00007f6ff7c5bbe5 in rspamd_vprintf_fstring (s=<optimized out>, fmt=<optimized out>, args=args@entry=0x7ffeaea24b30) at /usr/src/debug/rspamd-1.9.4/src/libutil/printf.c:569
569             return rspamd_vprintf_common (rspamd_printf_append_fstring, s, fmt, args);
(gdb) frame 7
#7  0x00007f6ff7c5bc84 in rspamd_printf_fstring (s=s@entry=0x7ffeaea24fb0, fmt=fmt@entry=0x7f6ff85169e4 "%.6f") at /usr/src/debug/rspamd-1.9.4/src/libutil/printf.c:560
560             r = rspamd_vprintf_fstring (s, fmt, args);
(gdb) frame 8
#8  0x00007f6ff7c644e9 in rspamd_fstring_emit_append_double (val=-3.6817595395344857e-68, ud=ud@entry=0x7ffeaea24fb0) at /usr/src/debug/rspamd-1.9.4/src/libutil/str_util.c:2368
2368                            rspamd_printf_fstring (buf, "%." G_STRINGIFY (MAX_PRECISION) "f",
(gdb) frame 9
#9  0x0000000000484d9f in ucl_emitter_common_elt (ctx=ctx@entry=0x7ffeaea24f00, obj=<optimized out>, obj@entry=0x7f6fee2807c0, first=<optimized out>, print_key=print_key@entry=true,
    compact=compact@entry=true) at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:411
411                     func->ucl_emitter_append_double (ucl_object_todouble (obj), func->ud);
(gdb) frame 10
#10 0x00000000004852c9 in ucl_emitter_common_start_object (ctx=ctx@entry=0x7ffeaea24f00, obj=0x7f6fee280680, print_key=print_key@entry=false, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:342
342                                     ucl_emitter_common_elt (ctx, cur, first, true, compact);
(gdb) frame 11
#11 0x0000000000484e32 in ucl_emitter_common_elt (ctx=ctx@entry=0x7ffeaea24f00, obj=<optimized out>, first=<optimized out>, print_key=print_key@entry=false, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:449
449                     ucl_emitter_common_start_object (ctx, obj, print_key, compact);
(gdb) frame 12
#12 0x00000000004850d7 in ucl_emitter_common_start_array (ctx=ctx@entry=0x7ffeaea24f00, obj=0x7f6fee280200, print_key=print_key@entry=true, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:272
272                             ucl_emitter_common_elt (ctx, cur, first, false, compact);
(gdb) frame 13
#13 0x0000000000484e62 in ucl_emitter_common_elt (ctx=ctx@entry=0x7ffeaea24f00, obj=<optimized out>, obj@entry=0x7f6fee280200, first=<optimized out>, print_key=print_key@entry=true,
    compact=compact@entry=true) at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:453
453                     ucl_emitter_common_start_array (ctx, obj, print_key, compact);
(gdb) frame 14
#14 0x00000000004852c9 in ucl_emitter_common_start_object (ctx=ctx@entry=0x7ffeaea24f00, obj=0x7f6fee280140, print_key=print_key@entry=false, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:342
342                                     ucl_emitter_common_elt (ctx, cur, first, true, compact);
(gdb) frame 15
#15 0x0000000000484e32 in ucl_emitter_common_elt (ctx=ctx@entry=0x7ffeaea24f00, obj=<optimized out>, first=<optimized out>, print_key=print_key@entry=false, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:449
449                     ucl_emitter_common_start_object (ctx, obj, print_key, compact);
(gdb) frame 16
#16 0x00000000004850d7 in ucl_emitter_common_start_array (ctx=ctx@entry=0x7ffeaea24f00, obj=0x7f6fed0d9ec0, print_key=print_key@entry=false, compact=compact@entry=true)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:272
272                             ucl_emitter_common_elt (ctx, cur, first, false, compact);
(gdb) frame 17
#17 0x0000000000484e62 in ucl_emitter_common_elt (ctx=0x7ffeaea24f00, obj=<optimized out>, first=<optimized out>, print_key=<optimized out>, compact=<optimized out>)
    at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:453
453                     ucl_emitter_common_start_array (ctx, obj, print_key, compact);
(gdb) frame 18
#18 0x0000000000485448 in ucl_object_emit_full (obj=obj@entry=0x7f6fed0d9ec0, emit_type=emit_type@entry=UCL_EMIT_JSON_COMPACT, emitter=emitter@entry=0x7ffeaea24f60,
    comments=comments@entry=0x0) at /usr/src/debug/rspamd-1.9.4/contrib/libucl/ucl_emitter.c:681
681                     my_ctx.ops->ucl_emitter_write_elt (&my_ctx, obj, true, false);
(gdb) frame 19
#19 0x00007f6ff7c67da9 in rspamd_ucl_emit_fstring_comments (obj=obj@entry=0x7f6fed0d9ec0, emit_type=emit_type@entry=UCL_EMIT_JSON_COMPACT, buf=buf@entry=0x7ffeaea24fb0,
    comments=comments@entry=0x0) at /usr/src/debug/rspamd-1.9.4/src/libutil/str_util.c:2393
2393            ucl_object_emit_full (obj, emit_type, &func, comments);
(gdb) frame 20
#20 0x00007f6ff7cf0392 in rspamd_controller_send_ucl (entry=entry@entry=0x7f6fed0de4e0, obj=obj@entry=0x7f6fed0d9ec0) at /usr/src/debug/rspamd-1.9.4/src/libserver/worker_util.c:486
486             rspamd_ucl_emit_fstring (obj, UCL_EMIT_JSON_COMPACT, &reply);
(gdb) frame 21
#21 0x0000000000415c82 in rspamd_controller_handle_symbols (conn_ent=conn_ent@entry=0x7f6fed0de4e0, msg=msg@entry=0x7f6fece018e0) at /usr/src/debug/rspamd-1.9.4/src/controller.c:850
850             rspamd_controller_send_ucl (conn_ent, top);
(gdb) frame 22
#22 0x00007f6ff7c4c409 in rspamd_http_router_finish_handler (conn=<optimized out>, msg=0x7f6fece018e0) at /usr/src/debug/rspamd-1.9.4/src/libutil/http_router.c:334
334                             return handler (entry, msg);
(gdb) frame 23
#23 0x00007f6ff7c4a295 in rspamd_http_on_message_complete (parser=<optimized out>) at /usr/src/debug/rspamd-1.9.4/src/libutil/http_connection.c:700
700                     ret = conn->finish_handler (conn, priv->msg);
(gdb) frame 24
#24 0x00007f6ff7d3d800 in http_parser_execute (parser=parser@entry=0x7f6ff5aaee38, settings=settings@entry=0x7f6ff5aaee58,
    data=0x7f6fecdcf810 "GET /symbols HTTP/1.1\r\nHost: 127.0.0.1:11334\r\nUser-Agent: DirectAdmin / 1.56.4\r\nAccept: */*\r\nAccept-Encoding: deflate, gzip\r\nReferer: https://server.example.net:2222/CMD_PLUGINS_ADMIN/rspamd/\r\nX-Forwar"..., len=len@entry=222) at /usr/src/debug/rspamd-1.9.4/contrib/http-parser/http_parser.c:1717
1717                  CALLBACK_NOTIFY(message_complete);
(gdb) frame 25
#25 0x00007f6ff7c4aec6 in rspamd_http_event_handler (fd=<optimized out>, what=<optimized out>, ud=0x7f6fecbd5590) at /usr/src/debug/rspamd-1.9.4/src/libutil/http_connection.c:942
942                             if (http_parser_execute (&priv->parser, &priv->parser_cb,
(gdb) frame 26
#26 0x00007f6ffbc23a14 in event_process_active_single_queue (activeq=0x7f6fecfbc4f0, base=0x7f6fecbd1d00) at event.c:1350
1350                            (*ev->ev_callback)(
(gdb) frame 27
#27 event_process_active (base=<optimized out>) at event.c:1420
1420                            c = event_process_active_single_queue(base, activeq);
(gdb) frame 28
#28 event_base_loop (base=0x7f6fecbd1d00, flags=flags@entry=0) at event.c:1621
1621                            int n = event_process_active(base);
(gdb) frame 29
#29 0x000000000041695f in start_controller_worker (worker=0x7f6fecbc4380) at /usr/src/debug/rspamd-1.9.4/src/controller.c:3928
3928            event_base_loop (ctx->ev_base, 0);
(gdb) frame 30
#30 0x00007f6ff7cf0b4d in rspamd_fork_worker (rspamd_main=0x7f6ff59d8000, cf=0x7f6ff5aa9380, index=0, ev_base=<optimized out>)
    at /usr/src/debug/rspamd-1.9.4/src/libserver/worker_util.c:749
749                     cf->worker->worker_start_func (wrk);
(gdb) frame 31
#31 0x000000000041ec96 in rspamd_fork_delayed_cb (signo=<optimized out>, what=<optimized out>, arg=0x7f6fecdff7c0) at /usr/src/debug/rspamd-1.9.4/src/rspamd.c:372
372             rspamd_fork_worker (w->rspamd_main, w->cf, w->oldindex,
(gdb) frame 32
#32 0x00007f6ffbc23a14 in event_process_active_single_queue (activeq=0x7f6fecfbc510, base=0x7f6fecbd1d00) at event.c:1350
1350                            (*ev->ev_callback)(
(gdb) frame 33
#33 event_process_active (base=<optimized out>) at event.c:1420
1420                            c = event_process_active_single_queue(base, activeq);
(gdb) frame 34
#34 event_base_loop (base=base@entry=0x7f6fecbd1d00, flags=flags@entry=0) at event.c:1621
1621                            int n = event_process_active(base);
(gdb) frame 35
#35 0x00000000004117fc in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /usr/src/debug/rspamd-1.9.4/src/rspamd.c:1541
1541            event_base_loop (ev_base, 0);
(gdb)

```

**Comment by vstakhov** [comment]
А вот теперь воспроизвел, спасибо.

**Comment by poralix** [comment]
Благодарю. После последнего апдейта полет нормальный. Падения прекратились.
