### ISSUE TITLE
[BUG] caught fatal signal 6 (maybe postscreen related)

### ISSUE THREAD

**Issue by leofeyer** [rspamd/rspamd#3088]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Since we have upgraded to version 2.0, rspamd crashes regularly on all of our servers. In all cases, the log contains a postscreen disconnect right before the crash, so maybe it is related:

```
Oct 15 08:08:57 m2 postfix/postscreen[24590]: CONNECT from [185.40.4.60]:56625 to [116.203.54.156]:25
Oct 15 08:08:57 m2 postfix/dnsblog[24685]: addr 185.40.4.60 listed by domain bad.psky.me as 198.54.117.197
Oct 15 08:08:57 m2 postfix/dnsblog[24685]: addr 185.40.4.60 listed by domain bad.psky.me as 198.54.117.198
Oct 15 08:08:57 m2 postfix/dnsblog[24685]: addr 185.40.4.60 listed by domain bad.psky.me as 198.54.117.199
Oct 15 08:08:57 m2 postfix/dnsblog[24685]: addr 185.40.4.60 listed by domain bad.psky.me as 198.54.117.200
Oct 15 08:08:57 m2 postfix/postscreen[24590]: PREGREET 11 after 0.05 from [185.40.4.60]:56625: EHLO User\r\n
Oct 15 08:08:57 m2 postfix/postscreen[24590]: DISCONNECT [185.40.4.60]:56625
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_crash_sig_handler: caught fatal signal 6(Aborted), pid: 30060, trace:
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 0: 00007F63D5CCA428: gsignal()+0x38
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 1: 00007F63D5CCC02A: abort()+0x16a
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 2: 00007F63D5CC2BD7: uselocale()+0x327
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 3: 00007F63D5CC2C82: __assert_fail()+0x42
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 4: 00007F63D606474E: ev_io_start()+0x18e
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 5: 00007F63D71F71FC: redisvAsyncCommand()+0x40c
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 6: 00007F63D71F7337: redisAsyncCommand()+0xc7
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 7: 00007F63D70F763E: rspamd_stat_ctx_register_async()+0x14e
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 8: 00007F63D6062F61: ev_invoke_pending()+0x71
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 9: 00007F63D6063D8C: ev_run()+0xe0c
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 10: 000000000041879A: start_rspamd_proxy()+0x21a
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 11: 00007F63D70F0786: rspamd_fork_worker()+0x926
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 12: 0000000000416FB8: main()+0x2508
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 13: 00007F63D6062F61: ev_invoke_pending()+0x71
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 14: 00007F63D6063D8C: ev_run()+0xe0c
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 15: 0000000000415551: main()+0xaa1
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 16: 00007F63D5CB5830: __libc_start_main()+0xf0
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 17: 000000000040AB69: _start()+0x29
Oct 15 08:08:59 m2 rspamd[30060]: <>; ; rspamd_print_crash: 18: 0000000000000000: <unknown>
Oct 15 08:08:59 m2 rspamd[22702]: <09b45a>; main; rspamd_check_termination_clause: rspamd_proxy process 30060 terminated abnormally by signal: Aborted but NOT created core file (throttled=no); core file limits: 0 current, -1 max
Oct 15 08:08:59 m2 rspamd[22702]: <09b45a>; main; rspamd_cld_handler: respawn process rspamd_proxy in lieu of terminated process with pid 30060
Oct 15 08:09:01 m2 rspamd[22702]: <09b45a>; main; rspamd_fork_worker: prepare to fork process rspamd_proxy (1); listen on: localhost
Oct 15 08:09:01 m2 rspamd[5972]: <09b45a>; main; rspamd_worker_set_limits: use system max file descriptors limit: 1024KiB cur and 1024KiB max
Oct 15 08:09:01 m2 rspamd[5972]: <09b45a>; main; rspamd_worker_set_limits: use system max core size limit: 0B cur and -1B max
Oct 15 08:09:01 m2 rspamd[5972]: <09b45a>; main; rspamd_fork_worker: starting rspamd_proxy process 5972 (1); listen on: localhost:11332
Oct 15 08:09:01 m2 rspamd[5972]: <xh349a>; lua; lua_redis.lua:1173: uploaded redis script to 127.0.0.1:6379 with id 5, sha: 3356099ff58c7e8893283c259278305d0d813a84
Oct 15 08:09:01 m2 rspamd[5972]: <xh349a>; lua; lua_redis.lua:1173: uploaded redis script to 127.0.0.1:6379 with id 2, sha: a43800941e2820ed8d764d50dfd9c142beddde68
Oct 15 08:09:01 m2 rspamd[5972]: <xh349a>; lua; lua_redis.lua:1173: uploaded redis script to 127.0.0.1:6379 with id 1, sha: 5fb4eaaa822d039a529304e93fca90de9a0931fa
Oct 15 08:09:01 m2 rspamd[5972]: <xh349a>; lua; lua_redis.lua:1173: uploaded redis script to 127.0.0.1:6379 with id 6, sha: da3a534c5a16cf973cfab2ba50c1fb8461a87093
Oct 15 08:09:01 m2 rspamd[5972]: <xh349a>; lua; lua_redis.lua:1173: uploaded redis script to 127.0.0.1:6379 with id 4, sha: b19d519e912f8c4d4a1f9fd972696ca72c72f366
Oct 15 08:09:01 m2 rspamd[5972]: <xh349a>; lua; lua_redis.lua:1173: uploaded redis script to 127.0.0.1:6379 with id 3, sha: abca34ba21057101e8177a22516d9bb3e3a387c4
```

### Versions

Ubuntu 16.04
Intel Xenon Skylake
Rspamd 2.0

**Comment by vstakhov** [comment]
https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
https://rspamd.com/doc/faq.html#what-can-i-do-with-core-files

**Comment by tjharman** [comment]
@leofeyer Are you running some sort of automated check against the milter port (i.e. librenms or similar?)
I saw a similar crash as this and reported it [here](https://github.com/rspamd/rspamd/issues/3083), but it's not considered a bug as I shouldn't be feeding the milter port anything that's not milter traffic.

[Also, don't use [bad.psky.me](https://www.spamhaus.org/organization/statement/015/fraudulent-dnsbl-uncovered-protected-sky-bad.psky.me)]

**Comment by leofeyer** [comment]
```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/rspamd...Reading symbols from /usr/lib/debug//usr/bin/rspamd...done.
done.
[New LWP 8267]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `rspamd: controller process (localhost:11334) '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fbd94721428 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt full
#0  0x00007fbd94721428 in raise () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007fbd9472302a in abort () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007fbd94719bd7 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#3  0x00007fbd94719c82 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#4  0x00007fbd94abb74e in ev_io_start (loop=0x7fbd8d479780, w=0x7fbd8669f548) at /rspamd-2.0/contrib/libev/ev.c:3899
        fd = -1
#5  0x00007fbd95c4e1fc in __redisAsyncCommand (ac=0x7fbd86aa2180, fn=<optimized out>, privdata=<optimized out>, 
    cmd=0x7fbd869c31f0 "*2\r\n$8\r\nSMEMBERS\r\n$15\r\nBAYES_SPAM_keys\r\n", len=40) at /rspamd-2.0/contrib/hiredis/async.c:648
        c = 0x7fbd86aa2180
        cstr = <optimized out>
        clen = <optimized out>
        p = <optimized out>
        ret = <optimized out>
        sname = <optimized out>
        astr = <optimized out>
        alen = <optimized out>
#6  0x00007fbd95c4e337 in redisvAsyncCommand (ac=<optimized out>, fn=<optimized out>, privdata=<optimized out>, format=<optimized out>, ap=0x3000000028)
    at /rspamd-2.0/contrib/hiredis/async.c:663
        cmd = 0x7fbd94721428 <raise+56> "H="
        len = 0
        status = <optimized out>
#7  redisAsyncCommand (ac=0x7fbd86aa2180, fn=0x7fbd95b5ac40 <rspamd_redis_stat_keys>, privdata=0x7fbd86b5be80, format=<optimized out>)
    at /rspamd-2.0/contrib/hiredis/async.c:672
        ap = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fffff7fe6b0, reg_save_area = 0x7fffff7fe5b0}}
#8  0x00007fbd95b4e63e in rspamd_async_elt_on_timer (loop=0x7fbd8d479780, w=0x7fbd869e9ec8, revents=6) at /rspamd-2.0/src/libstat/stat_config.c:525
        elt = 0x7fbd869e9eb0
        jittered_time = <optimized out>
#9  0x00007fbd94ab9f61 in ev_invoke_pending (loop=0x7fbd8d479780) at /rspamd-2.0/contrib/libev/ev.c:3340
No locals.
#10 0x00007fbd94abad8c in ev_run (loop=0x7fbd8d479780, flags=<optimized out>) at /rspamd-2.0/contrib/libev/ev.c:3744
No locals.
#11 0x000000000040be75 in ev_loop (flags=0, loop=<optimized out>) at /rspamd-2.0/contrib/libev/ev.h:822
No locals.
#12 start_controller_worker (worker=<optimized out>) at /rspamd-2.0/src/controller.c:3931
        save_stats_interval = 60
        ctx = <optimized out>
        i = <optimized out>
        mctx = <optimized out>
        iter = {dummy1 = 0x7fbd8d466360, dummy2 = 0x7fffff7fe810, dummy3 = 0x7fbd94801876 <clock_gettime+38>, dummy4 = 8, dummy5 = 0, dummy6 = 0x7fbd00000003}
        key = 0x7fbd962d3d26
        value = 0x7fbd86ad2068
        m = <optimized out>
#13 0x00007fbd95b47786 in rspamd_fork_worker (rspamd_main=<optimized out>, cf=0x7fbd8d51c380, index=0, ev_base=<optimized out>, term_handler=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at /rspamd-2.0/src/libserver/worker_util.c:948
        wrk = 0x7fbd869ed700
        rc = <optimized out>
#14 0x0000000000416d23 in spawn_worker_type (rspamd_main=0x7fbd8d449280, event_loop=0x7fbd94cc2818 <default_loop_struct>, cf=0x7fbd8d51c380)
    at /rspamd-2.0/src/rspamd.c:554
        i = 0
#15 0x000000000041665e in spawn_workers (rspamd_main=<optimized out>, ev_base=0x7fbd94cc2818 <default_loop_struct>) at /rspamd-2.0/src/rspamd.c:637
        listen_ok = <optimized out>
        seen_mandatory_workers = 0x7fbd893f9820
        cur = <optimized out>
        cf = <optimized out>
        bcf = <optimized out>
        key = <optimized out>
        p = <optimized out>
        ls = <optimized out>
        wrk = <optimized out>
        i = <optimized out>
        cw = <optimized out>
#16 0x000000000041548c in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /rspamd-2.0/src/rspamd.c:1469
        skip_pid = 1
        rspamd_main = 0x7fbd8d449280
        i = <optimized out>
        type = <optimized out>
        sigpipe_act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {4096, 0 <repeats 15 times>}}, sa_flags = 0, 
          sa_restorer = 0x1}
        control_addr = <optimized out>
        event_loop = 0x7fbd94cc2818 <default_loop_struct>
```
