### ISSUE TITLE
[BUG] crash in rspamc in exit code

### ISSUE THREAD

**Issue by darix** [rspamd/rspamd#3123]
```
(gdb) bt full
#0  rspamd_mempool_delete (pool=0x0) at /usr/src/debug/rspamd-2.0-lp151.1.1.x86_64/src/libutil/mem_pool.c:676
        cur = 0x0
        tmp = <optimized out>
        destructor = <optimized out>
        ptr = <optimized out>
        i = <optimized out>
        len = <optimized out>
#1  0x00007f24eb2652b3 in _dl_fini () at dl-fini.c:235
        array = 0x7f24eae4c650
        i = <optimized out>
        l = 0x7f24eb4684e0
        maps = <optimized out>
        i = <optimized out>
        l = <optimized out>
        nmaps = <optimized out>
        nloaded = <optimized out>
        ns = 0
        do_audit = <optimized out>
        __PRETTY_FUNCTION__ = "_dl_fini"
#2  0x00007f24eaed3d78 in __run_exit_handlers (status=0, listp=0x7f24eb24f6f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:83
        atfct = <optimized out>
        onfct = <optimized out>
        cxafct = <optimized out>
        f = <optimized out>
        cur = <optimized out>
#3  0x00007f24eaed3dca in __GI_exit (status=<optimized out>) at exit.c:105
No locals.
#4  0x00007f24eaebbf91 in __libc_start_main (main=0x55ecf45e0ed0 <main>, argc=8, argv=0x7ffcf12dd838, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcf12dd828)
    at ../csu/libc-start.c:342
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -6158806706091394267, 94476200451936, 140724354799664, 0, 0, -96951143678018779, -65380268499469531}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x7ffcf12dd880, 0x7f24eb47c110}, data = {prev = 0x0, cleanup = 0x0, canceltype = -248653696}}}
        not_first_call = <optimized out>
#5  0x000055ecf45e1f8a in _start () at ../sysdeps/x86_64/start.S:120
No locals.
```

**Comment by darix** [comment]
fixed in 2.1
