### ISSUE TITLE
[BUG] Crash if cannot connect to redis with unix socket 

### ISSUE THREAD

**Issue by AMDG2** [rspamd/rspamd#3130]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When connecting to redis over unix socket rspamd crashes if permissions are not sufficient to open the socket. One assertion fails:

```
rspamd: /build/rspamd/src/rspamd/contrib/libev/ev.c :3899 : ev_io_start: l'assertion « ("libev: ev_io_start called with negative fd", fd >= 0) » a échoué.
```

### Steps to Reproduce

1. Configure rspamd to connect to redis via unix socket
2. Make sure rspamd user cannot access the unix socket (`sudo -u rspamd redis-cli -s /run/redis/redis.sock` should fail to connect)
3. Start rspamd
4. rspamd will crash because of failed assertion.

**Expected behavior**
An explicit error message should appear and rspamd should either stop gracefully or continue in degraded mode.

### Versions

- rspamd: 2.0
- OS: ArchLinux
- Arch: x86_64
- Redis: 5.0.6

### Additional Information

Rspamd is running under rspamd:rspamd user and group. It crash only when rspamd user is not in redis group.

```
$ ls -lah /run/redis/
total 0
drwxr-xr-x  2 redis redis  60 30 oct.  09:26 .
drwxr-xr-x 28 root  root  780 30 oct.  10:54 ..
srwxrwx---  1 redis redis   0 30 oct.  09:26 redis.sock
```

Coredump:
```
# coredumpctl info 26979
           PID: 26979 (rspamd)
           UID: 961 (rspamd)
           GID: 961 (rspamd)
        Signal: 6 (ABRT)
     Timestamp: Wed 2019-10-30 09:51:03 CET (3h 20min ago)
  Command Line: rspamd: rspamd_proxy process (localhost:11332)
    Executable: /usr/bin/rspamd-2.0
 Control Group: /system.slice/rspamd.service
          Unit: rspamd.service
         Slice: system.slice
       Boot ID: ********
    Machine ID: ********
      Hostname: ********
       Storage: /var/lib/systemd/coredump/core.rspamd.961.5bd8d96e2a4742198458e158742cba48.26979.1572425463000000000000.lz4
       Message: Process 26979 (rspamd) of user 961 dumped core.

                Stack trace of thread 26979:
                #0  0x00007f0244bd8f25 raise (libc.so.6)
                #1  0x00007f0244bc2897 abort (libc.so.6)
                #2  0x00007f0244bc2767 __assert_fail_base.cold (libc.so.6)
                #3  0x00007f0244bd1526 __assert_fail (libc.so.6)
                #4  0x00007f0243eb7c86 ev_io_start (librspamd-ev.so)
                #5  0x00007f02446a7e05 n/a (librspamd-server.so)
                #6  0x00007f02446a9c8a redisvAsyncCommand (librspamd-server.so)
                #7  0x00007f02446a9d5b redisAsyncCommand (librspamd-server.so)
                #8  0x00007f024479c2ee n/a (librspamd-server.so)
                #9  0x00007f0243eb5a16 ev_invoke_pending (librspamd-ev.so)
                #10 0x00007f0243eba11f ev_run (librspamd-ev.so)
                #11 0x000055e334d6c0e4 start_rspamd_proxy (rspamd-2.0)
                #12 0x00007f02447a4f66 rspamd_fork_worker (librspamd-server.so)
                #13 0x000055e334d7076b n/a (rspamd-2.0)
                #14 0x00007f0243eb5a16 ev_invoke_pending (librspamd-ev.so)
                #15 0x00007f0243eba11f ev_run (librspamd-ev.so)
                #16 0x000055e334d01a2c main (rspamd-2.0)
                #17 0x00007f0244bc4153 __libc_start_main (libc.so.6)
                #18 0x000055e334d01e2e _start (rspamd-2.0)
```

The issue is probably happening here: <https://github.com/rspamd/rspamd/blob/master/src/libserver/redis_pool.c#L235>. I guess the `redisAsyncConnectUnix` doens't set any error flag and then when we try to send a command to redis it fails because file description is invalid (negative as said in the assert).

**Comment by vstakhov** [comment]
Outdated version, closing.

**Comment by gringus** [comment]
More recent stacktrace for:

OS: Gentoo Linux
Redis: 7.0.12
Rspamd daemon version 3.5

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.0-beta3)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```
(gdb) bt full
#0  rspamd_redis_get_stat (runtime=0x0, ctx=0xcd9fbb6f2e0) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/libstat/backends/redis_backend.c:2047
        rt = 0x0
        st = <optimized out>
        redis = <optimized out>
#1  0x00006728181e490b in rspamd_stat_statistics (task=task@entry=0xcda00d7cbb0, cfg=<optimized out>, total_learns=total_learns@entry=0xcda00d7ceb8, target=target@entry=0xcda00d7cea8)
    at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/libstat/stat_process.c:1208
        st_ctx = 0xcd9fbb6f190
        cl = 0xcd9fbb6f250
        st = 0xcd9fbb6f2b0
        backend_runtime = 0x0
        res = 0xcda00d7dde0
        elt = <optimized out>
        learns = 0
        i = 0
        j = 0
        id = <optimized out>
        __func__ = "rspamd_stat_statistics"
#2  0x00000cd9d0f6ac9e in rspamd_controller_handle_metrics_common (do_reset=0, msg=<optimized out>, conn_ent=<optimized out>) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/controller.c:3216
        session = 0xcd9fbb6e730
        top = 0xcd9fe1ea8f0
        sub = <optimized out>
        i = <optimized out>
        uptime = <optimized out>
        spam = <optimized out>
        ham = <optimized out>
        mem_st = {pools_allocated = 36, pools_freed = 3, bytes_allocated = 26142992, chunks_allocated = 233, shared_chunks_allocated = 3, chunks_freed = 0, oversized_chunks = 1, fragmented_size = 0}
        stat = 0x780e04044ac0
        stat_copy = {messages_scanned = 143299, actions_stat = {0, 131852, 0, 947, 4938, 5562}, connections_count = 0, control_connections_count = 0, messages_learned = 113, avg_time = {cur_slot = 0, avg_time = {nan(0x400000) <repeats 31 times>}}}
        ctx = <optimized out>
        task = 0xcda00d7cbb0
        cbdata = 0xcda00d7ce90
#3  rspamd_controller_handle_metrics (msg=<optimized out>, conn_ent=<optimized out>) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/controller.c:3236
        session = <optimized out>
#4  rspamd_controller_handle_metrics (conn_ent=<optimized out>, msg=<optimized out>) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/controller.c:3228
        session = <optimized out>
#5  0x00006728181808d2 in rspamd_http_router_finish_handler (conn=<optimized out>, msg=0xcd9fbb6e110) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/libserver/http/http_router.c:346
        entry = 0xcda00ce1620
        handler = 0xcd9d0f6a7e0 <rspamd_controller_handle_metrics>
        found = 0xcd9d0f6a7e0 <rspamd_controller_handle_metrics>
        err = <optimized out>
        lookup = {len = 8, begin = 0xcd9fbb6e240 "\252\252\252\252\332\f"}
        encoding = <optimized out>
        u = {field_set = 8, port = 0, field_data = {{off = 1, len = 0}, {off = 32, len = 0}, {off = 0, len = 0}, {off = 0, len = 8}, {off = 30734, len = 0}, {off = 3, len = 0}, {off = 0, len = 0}}}
        i = <optimized out>
        re = <optimized out>
        router = 0xcd9fe0353e0
        pathbuf = 0xcd9fbb6e240 "\252\252\252\252\332\f"
        __func__ = "rspamd_http_router_finish_handler"
#6  0x000067281817ead0 in rspamd_http_on_message_complete (parser=<optimized out>) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/libserver/http/http_connection.c:699
        conn = 0xcd9fe1547b0
        priv = 0xcd9fbb6dfc0
        ret = <optimized out>
        mode = <optimized out>
        __func__ = "rspamd_http_on_message_complete"
        _g_boolean_var_8 = <optimized out>
#7  0x000067281829223a in http_parser_execute (parser=parser@entry=0xcd9fbb6dff8, settings=settings@entry=0xcd9fbb6e018, 
    data=0xcd9fbe77100 "GET /metrics HTTP/1.1\r\nHost: 127.0.0.1:11334\r\nUser-Agent: Prometheus/2.43.0\r\nAccept: application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0"..., len=len@entry=286)
    at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/contrib/http-parser/http_parser.c:1717
        c = <optimized out>
        ch = <optimized out>
        unhex_val = <optimized out>
        p = <optimized out>
        header_field_mark = <optimized out>
        header_value_mark = <optimized out>
        url_mark = <optimized out>
        body_mark = <optimized out>
        status_mark = <optimized out>
        __PRETTY_FUNCTION__ = "http_parser_execute"
        reexecute_byte = <optimized out>
#8  0x000067281817f736 in rspamd_http_event_handler (fd=<optimized out>, what=<optimized out>, ud=0xcd9fe1547b0) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/libserver/http/http_connection.c:955
        conn = 0xcd9fe1547b0
        priv = 0xcd9fbb6dfc0
        pbuf = 0xcda0457bc40
        d = 0xcd9fbe77100 "GET /metrics HTTP/1.1\r\nHost: 127.0.0.1:11334\r\nUser-Agent: Prometheus/2.43.0\r\nAccept: application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0"...
        r = 286
        err = <optimized out>
        __func__ = "rspamd_http_event_handler"
#9  0x00006728185ceb8d in ev_invoke_pending (loop=0xcd9feb5a4f0) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/contrib/libev/ev.c:3807
        p = <optimized out>
#10 0x00006728185d275b in ev_run (flags=0, loop=0xcd9feb5a4f0) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/contrib/libev/ev.c:4228
        __PRETTY_FUNCTION__ = "ev_run"
        waittime = <optimized out>
        sleeptime = <optimized out>
        prev_mn_now = <optimized out>
        to = <optimized out>
        to = <optimized out>
#11 ev_run (loop=0xcd9feb5a4f0, flags=flags@entry=0) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/contrib/libev/ev.c:4058
        __PRETTY_FUNCTION__ = "ev_run"
        waittime = <optimized out>
        sleeptime = <optimized out>
        prev_mn_now = <optimized out>
        to = <optimized out>
        to = <optimized out>
#12 0x00000cd9d0f68dae in ev_loop (flags=0, loop=<optimized out>) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/contrib/libev/ev.h:830
No locals.
#13 start_controller_worker (worker=<optimized out>) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/controller.c:4275
        ctx = 0x672813209820
        mctx = <optimized out>
        iter = {dummy1 = 0xcd9fb98ab30, dummy2 = 0x780e04044fc0, dummy3 = 0x780e04044f80, dummy4 = 8, dummy5 = -1713711047, dummy6 = 0xcd900000003}
        key = 0x67281833571c
        value = 0xcd9fb773f50
        i = <optimized out>
        m = <optimized out>
        __func__ = "start_controller_worker"
#14 0x0000672818174be5 in rspamd_handle_child_fork (listen_sockets=<optimized out>, cf=0xcd9fac86a90, rspamd_main=0xcd9fac04f10, wrk=0xcd9fc129e40) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/libserver/worker_util.c:1188
        rlim = {rlim_cur = 104857600, rlim_max = 104857600}
        k = 0xda10b567fa5e638c
        rc = <optimized out>
        it = {dummy1 = 0xcd9fac75c40, dummy2 = 0x3, dummy3 = 0xcd9fac75c40, dummy4 = 8, dummy5 = 0, dummy6 = 0x2}
        v = 0xcd9fb8f3aa0
        cur = <optimized out>
        rc = <optimized out>
        rlim = <optimized out>
        __func__ = "rspamd_handle_child_fork"
        it = <optimized out>
        k = <optimized out>
        v = <optimized out>
        cur = <optimized out>
        elt = <optimized out>
        our = <optimized out>
        cur = <optimized out>
        ls = <optimized out>
        ls = <optimized out>
        listen_conf_stringified = <optimized out>
        cur_conf = <optimized out>
#15 rspamd_fork_worker (rspamd_main=rspamd_main@entry=0xcd9fac04f10, cf=cf@entry=0xcd9fac86a90, index=index@entry=0, ev_base=ev_base@entry=0x6728185d9720 <default_loop_struct>, term_handler=term_handler@entry=0xcd9d0f74c80 <rspamd_cld_handler>, 
    listen_sockets=<optimized out>) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/libserver/worker_util.c:1305
        wrk = 0xcd9fc129e40
        __func__ = "rspamd_fork_worker"
#16 0x00000cd9d0f7462a in spawn_worker_type (rspamd_main=rspamd_main@entry=0xcd9fac04f10, event_loop=event_loop@entry=0x6728185d9720 <default_loop_struct>, cf=0xcd9fac86a90) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/rspamd.c:630
        i = 0
        __func__ = "spawn_worker_type"
#17 0x00000cd9d0f746ee in spawn_workers (rspamd_main=0xcd9fac04f10, ev_base=0x6728185d9720 <default_loop_struct>) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/rspamd.c:730
        cur = <optimized out>
        ls = <optimized out>
        cf = <optimized out>
        p = <optimized out>
        key = <optimized out>
        bcf = <optimized out>
        listen_ok = <optimized out>
        seen_mandatory_workers = 0xcd9fb8f3c20
        cw = <optimized out>
        wrk = <optimized out>
        i = <optimized out>
        __func__ = "spawn_workers"
#18 0x00000cd9d0f66506 in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /var/tmp/portage/mail-filter/rspamd-3.5-r1/work/rspamd-3.5/src/rspamd.c:1620
        i = <optimized out>
        res = 0
        signals = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        sigpipe_act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {4096, 4685809440684, 18584323490991, 280620278290652, 514897859433496, 515344536032384, 515791212631272, 516237889230160, 516684565829048, 517131242427936, 8, 
              132001592267584, 0, 132001592267600, 5, 4}}, sa_flags = 0, sa_restorer = 0x6728182dad60 <lc_map>}
        pworker = <optimized out>
        type = <optimized out>
        control_addr = 0xcd9fb8f3b00
        event_loop = 0x6728185d9720 <default_loop_struct>
        rspamd_main = 0xcd9fac04f10
        skip_pid = 1
        control_signals = {__val = {2561, 515451910214809, 515898586813697, 516345263412585, 516791940011473, 517238616610361, 4694399375009, 23626615100737, 41175851472493, 308876868125474, 36734855348024, 514893564466199, 515340241065087, 515786917663975, 
            516233594262863, 516680270861751}}
        __func__ = "main"
```
Error log is filled up with:
```
2023-07-18 18:12:17 #500639(controller) redis_async_new: cannot connect to redis /run/redis/redis.sock (port 0): No such file or directory
2023-07-18 18:12:17 #500639(controller) rspamd_lua_redis_prepare_connection: cannot connect to redis (OS error): No such file or directory
2023-07-18 18:12:17 #500639(controller) lua; lua_redis.lua:1231: cannot execute redis request to load script on /run/redis/redis.sock
2023-07-18 18:12:17 #500639(controller) redis_async_new: cannot connect to redis /run/redis/redis.sock (port 0): No such file or directory
2023-07-18 18:12:17 #500639(controller) rspamd_lua_redis_prepare_connection: cannot connect to redis (OS error): No such file or directory
2023-07-18 18:12:17 #500639(controller) lua; lua_redis.lua:1231: cannot execute redis request to load script on /run/redis/redis.sock
2023-07-18 18:12:17 #500639(controller) redis_async_new: cannot connect to redis /run/redis/redis.sock (port 0): No such file or directory
2023-07-18 18:12:17 #500639(controller) rspamd_lua_redis_prepare_connection: cannot connect to redis (OS error): No such file or directory
2023-07-18 18:12:17 #500639(controller) lua; lua_redis.lua:1231: cannot execute redis request to load script on /run/redis/redis.sock
2023-07-18 18:12:17 #500639(controller) redis_async_new: cannot connect to redis /run/redis/redis.sock (port 0): No such file or directory
2023-07-18 18:12:17 #500639(controller) rspamd_lua_redis_prepare_connection: cannot connect to redis (OS error): No such file or directory
2023-07-18 18:12:17 #500639(controller) lua; lua_redis.lua:1231: cannot execute redis request to load script on /run/redis/redis.sock
2023-07-18 18:12:17 #500639(controller) redis_async_new: cannot connect to redis /run/redis/redis.sock (port 0): No such file or directory
2023-07-18 18:12:17 #500639(controller) rspamd_lua_redis_prepare_connection: cannot connect to redis (OS error): No such file or directory
2023-07-18 18:12:17 #500639(controller) lua; lua_redis.lua:1231: cannot execute redis request to load script on /run/redis/redis.sock
2023-07-18 18:12:17 #500639(controller) redis_async_new: cannot connect to redis /run/redis/redis.sock (port 0): No such file or directory
2023-07-18 18:12:17 #500639(controller) rspamd_lua_redis_prepare_connection: cannot connect to redis (OS error): No such file or directory
2023-07-18 18:12:17 #500639(controller) lua; lua_redis.lua:1231: cannot execute redis request to load script on /run/redis/redis.sock
2023-07-18 18:12:17 #500639(controller) <tqpgc4>; lua; lua_redis.lua:1209: cannot upload script to 127.0.0.1:6379: Connection refused; registered from: /usr/share/rspamd/plugins/reputation.lua:982
2023-07-18 18:12:17 #500639(controller) <tqpgc4>; lua; lua_redis.lua:1209: cannot upload script to 127.0.0.1:6379: Connection refused; registered from: /usr/share/rspamd/plugins/reputation.lua:982
2023-07-18 18:12:17 #500639(controller) <tqpgc4>; lua; lua_redis.lua:1209: cannot upload script to 127.0.0.1:6379: Connection refused; registered from: /usr/share/rspamd/plugins/reputation.lua:934
2023-07-18 18:12:17 #500639(controller) <tqpgc4>; lua; lua_redis.lua:1209: cannot upload script to 127.0.0.1:6379: Connection refused; registered from: /usr/share/rspamd/plugins/reputation.lua:982
2023-07-18 18:12:17 #500639(controller) <tqpgc4>; lua; lua_redis.lua:1209: cannot upload script to 127.0.0.1:6379: Connection refused; registered from: /usr/share/rspamd/plugins/reputation.lua:934
2023-07-18 18:12:17 #500639(controller) <tqpgc4>; lua; lua_redis.lua:1209: cannot upload script to 127.0.0.1:6379: Connection refused; registered from: /usr/share/rspamd/plugins/reputation.lua:982
2023-07-18 18:12:17 #500639(controller) <tqpgc4>; lua; lua_redis.lua:1209: cannot upload script to 127.0.0.1:6379: Connection refused; registered from: /usr/share/rspamd/plugins/reputation.lua:934
2023-07-18 18:12:17 #500639(controller) <tqpgc4>; lua; lua_redis.lua:1209: cannot upload script to 127.0.0.1:6379: Connection refused; registered from: /usr/share/rspamd/plugins/reputation.lua:934
```
The very same behavior is observed when `redis` is not running during `rspamd` start or when `redis` goes down (eg. gets stopped) during normal `rspamd` operation.
