### ISSUE TITLE
[BUG] Signtool crashes

### ISSUE THREAD

**Issue by griff** [rspamd/rspamd#3456]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

Whenever i try to use `rspamadm signtool` it crashes with the message `stack smashing detected`.

### Steps to Reproduce

Whenever I try to run signtool. Like this:
```
rspamadm signtool -k keypair.ucl site/lists/combined_all
```

I get this output:
```
signed site/lists/combined_all; stored hash in site/lists/combined_all.sig
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```

### Versions

`Rspamd daemon version 2.5`
`Rspamd daemon version 2.2`

Running on NixOS or on Ubuntu but installed using Nix.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
```
(gdb) bt full
#0  0x00007ff1ec89c17a in raise () from /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libc.so.6
No symbol table info available.
#1  0x00007ff1ec886548 in abort () from /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libc.so.6
No symbol table info available.
#2  0x00007ff1ec8dd768 in __libc_message () from /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libc.so.6
No symbol table info available.
#3  0x00007ff1ec96b06d in __fortify_fail_abort () from /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libc.so.6
No symbol table info available.
#4  0x00007ff1ec96b022 in __stack_chk_fail () from /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libc.so.6
No symbol table info available.
#5  0x000000000042126a in rspamadm_sign_file (fname=0x7ff1e3363b60 "site/lists/combined_all", kp=0x7ff1ec3e6680) at /build/source/src/rspamadm/signtool.c:312
        fd_sig = 24
        fd_input = <optimized out>
        sig = "\tg\363OY\020\021\020:1M\223\201\337\065\022\023\231'\303xS%\361\323EܖϾ/(pec\a(N\363\332{\242\070\357\017\234\064\064@Q\250\030\037\216r|(\353\344N( u\001\064\062.159.3"
        map = 0x7ff1ec659000 <error: Cannot access memory at address 0x7ff1ec659000>
        sigpath = "site/lists/combined_all.sig\000\361\177\000\000\200\037\254\217\374\177\000\000\320\364\"\354\361\177\000\000\210\001\000\000\000\000\000\000\000\300e\354\361\177\000\000/vagrant/keypair.ucl\000\000\000\000\325\024\024\357\361\177\000\000`\374!\354\361\177\000\000\fa\276\354\361\177\000\000\b`\350@\000\000\000\000\360\330\377\377\000\000\000\000\024\000\000\000\000\000\000\000/\000\000\000\000\000\000\000`\374!\354\361\177\000\000dW\254\354\361\177\000\000\017\000\000\000\000\000\000\000`\374!\354\361\177", '\000' <repeats 18 times>, "@);\354\361\177\000\000"...
        pub_fp = <optimized out>
        st = {st_dev = 45, st_ino = 13, st_nlink = 1, st_mode = 33188, st_uid = 501, st_gid = 20, __pad0 = 0, st_rdev = 0, st_size = 12535, st_blksize = 1024, 
          st_blocks = 25, st_atim = {tv_sec = 1596114604, tv_nsec = 0}, st_mtim = {tv_sec = 1595042885, tv_nsec = 0}, st_ctim = {tv_sec = 1595042885, 
            tv_nsec = 0}, __glibc_reserved = {0, 0, 0}}
        sk = <optimized out>
        __func__ = "rspamadm_sign_file"
#6  0x322f302e36312e39 in ?? ()
No symbol table info available.
#7  0x31322e3933310a37 in ?? ()
No symbol table info available.
#8  0x322f302e37312e39 in ?? ()
No symbol table info available.
```

**Comment by vstakhov** [comment]
Reproduced... This bug is pretty bad and it can also affect ed25519 signatures in dkim module.

**Comment by vstakhov** [comment]
To clarify: ed25519 signing.
