### ISSUE TITLE
[BUG] Segmentation fault after every stop

### ISSUE THREAD

**Issue by AlexeySa** [rspamd/rspamd#3930]
**Describe the bug**
Segfault crash after every stop rspamd.

### Steps to Reproduce

1. Install Centos 8.4
2. `curl https://rspamd.com/rpm-stable/centos-8/rspamd.repo > /etc/yum.repos.d/rspamd.repo`
3. `yum install rspamd`
4. `systemctl start rspamd`
5. `systemctl stop rspamd`

### Versions
Rspamd 3.0.2 (from https://rspamd.com/rpm-stable/centos-8/)
Centos 8.4

### Additional Information

Rspamd log:
```2021-10-09 21:57:33 #14289(main) <ee6192>; main; rspamd_term_handler: catch termination signal, waiting for 4 children for 16.00 seconds
2021-10-09 21:57:33 #14290(rspamd_proxy) <ee6192>; main; rspamd_worker_term_handler: terminating after receiving signal Terminated
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 14290, trace:
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 0: 00007FAD39F6680D: malloc_usable_size()+0x5a81d
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 1: 00007FAD39F67B5B: malloc_usable_size()+0x5bb6b
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 2: 00007FAD39F07739: calloc()+0xc89
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 3: 00007FAD34B0C452: g_free()+0x12
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 4: 00007FAD34AD8C03: g_ptr_array_foreach()+0xd3
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 5: 00007FAD3987195B: rspamd_mempool_destructors_enforce()+0x2b
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 6: 00007FAD39858E4E: rspamd_config_free()+0x11e
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 7: 000000000040D810: <unknown>
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 8: 00007FAD39804594: rspamd_fork_worker()+0x7d4
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 9: 0000000000412D4D: <unknown>
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 10: 00000000004132AA: <unknown>
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 11: 000000000040B864: <unknown>
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 12: 00007FAD33DE7493: __libc_start_main()+0xf3
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_print_crash: 13: 000000000040BE5E: <unknown>
2021-10-09 21:57:33 #14290(rspamd_proxy) rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
```

Backtrace:
```(gdb) bt
#0  je_tcache_bin_flush_small (tsd=<optimized out>, tcache=<optimized out>, tbin=0x7fad3a5b1670, binind=<optimized out>,
    rem=<optimized out>) at src/tcache.c:187
#1  0x00007fad39f67b5b in je_tcache_event_hard (tsd=<optimized out>, tcache=0x7fad3a5b15d0) at src/tcache.c:55
#2  0x00007fad39f07739 in tcache_event (tcache=<optimized out>, tsd=<optimized out>) at include/jemalloc/internal/tcache_inlines.h:37
#3  tcache_dalloc_large (slow_path=<optimized out>, binind=<optimized out>, ptr=<optimized out>, tcache=<optimized out>,
    tsd=<optimized out>) at include/jemalloc/internal/tcache_inlines.h:212
#4  arena_dalloc_large (slow_path=<optimized out>, szind=<optimized out>, tcache=<optimized out>, ptr=<optimized out>,
    tsdn=<optimized out>) at include/jemalloc/internal/arena_inlines_b.h:276
#5  arena_dalloc (slow_path=<optimized out>, alloc_ctx=<optimized out>, tcache=<optimized out>, ptr=<optimized out>, tsdn=<optimized out>)
    at include/jemalloc/internal/arena_inlines_b.h:323
#6  idalloctm (slow_path=<optimized out>, is_internal=<optimized out>, alloc_ctx=<optimized out>, tcache=<optimized out>,
    ptr=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/jemalloc_internal_inlines_c.h:118
#7  ifree (slow_path=<optimized out>, tcache=<optimized out>, ptr=<optimized out>, tsd=<optimized out>) at src/jemalloc.c:2589
#8  je_free_default (ptr=0x7fad2f8c4500) at src/jemalloc.c:2799
#9  0x00007fad34b0c452 in g_free () from /lib64/libglib-2.0.so.0
#10 0x00007fad34ad8c03 in ptr_array_free () from /lib64/libglib-2.0.so.0
#11 0x00007fad3987195b in rspamd_mempool_destructors_enforce (pool=0x7fad30600900)
    at /usr/src/debug/rspamd-3.0-2.x86_64/src/libutil/mem_pool.c:780
#12 0x00007fad39858e4e in rspamd_config_free (cfg=0x7fad306009a0) at /usr/src/debug/rspamd-3.0-2.x86_64/src/libserver/cfg_utils.c:319
#13 0x000000000040ba7d in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>)
    at /usr/src/debug/rspamd-3.0-2.x86_64/src/rspamd.c:1630
```

**Comment by vstakhov** [comment]
You can check experimental packages to see if it is fixed or not.

**Comment by GieltjE** [comment]
@mrueg Got a 3.1 update on Debian via the official repository, guess it will be out officially any minute now.
