### ISSUE TITLE
rspamadm problem - cannot run the configwizard

### ISSUE THREAD

**Issue by MicroProduction** [rspamd/rspamd#4063]
Hello, searched for hours and tried plenty of things
Don't know if this is a bug or I am doing something wrong... Nice if I can get a solution
Ubuntu 20.04 - rspamd 3.1 is loading configuration, build id: release
running "sudo rspamadm configwizard" generates a "Segmentation fault" error
Here is what I get after typing in the command:
Welcome to the configuration tool
We use /etc/rspamd/rspamd.conf configuration file, writing results to /etc/rspamd
Modules enabled: metadata_exporter, fuzzy_check, greylist, regexp, replies, whitelist, history_redis, hfilter, milter_headers, settings, once_received, maillist, spf, forged_recipients, force_actions, arc, dmarc, trie, asn, emails, neural, dkim_signing, mid, multimap, mime_types, dkim, ratelimit, bayes_expiry, chartable, phishing, rbl
Modules disabled (explicitly): rspamd_update, p0f, external_relay, aws_s3, spamtrap, dcc, http_headers, mx_check
Modules disabled (unconfigured): antivirus, external_services, clustering, dynamic_conf, url_redirector, fuzzy_collect, metric_exporter, ip_score, spamassassin, reputation, maps_stats, elastic, clickhouse
Modules disabled (no Redis):
Modules disabled (experimental):
Modules disabled (failed):
Segmentation fault

**Comment by janedenone** [comment]
I get the same result with Ubuntu 20.04/rspamd 3.1.

**Comment by cpohle1983** [comment]
Me as well, same setup

**Comment by MicroProduction** [comment]
Hello to all the "GitHubbers"
Has someone tried with a previous version ????
Is it possible to switch to another version to get rid of the problem.
Has someone found a solution.
Thanks in advance if we get a solution and get that problem solved.
JMM (Newbie GitHubber)

**Comment by vstakhov** [comment]
This issue is report is invalid, please read the documentation: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed and please do not skip the issue template.

**Comment by srinathman** [comment]
I was having the same error when using stable and experimental repos.  But when using the asan repo, the wizard apparently finished but giving the following error at the end:

```
Apply changes?[Y/n]: y
Create file /etc/rspamd/local.d/redis.conf
Create file /etc/rspamd/local.d/worker-controller.inc
Create file /etc/rspamd/local.d/dkim_signing.conf
3 changes applied, the wizard is finished now
*** Please reload the Rspamd configuration ***

=================================================================
==57534==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 288 byte(s) in 3 object(s) allocated from:
    #0 0x56171c8dc2c8 in __interceptor_malloc (/usr/bin/rspamadm+0x1592c8)
    #1 0x7fa308358294  (/lib/x86_64-linux-gnu/libpcre2-8.so.0+0x11294)
    #2 0x7fa30a08ba9a in rspamd_regexp_new_len src/libutil/regexp.c:509
    #3 0x7fa30a08bf50 in rspamd_regexp_new src/libutil/regexp.c:533
    #4 0x7fa309ce3ea9 in rspamd_mime_expr_parse_regexp_atom src/libmime/mime_expressions.c:504
    #5 0x7fa309ce4870 in rspamd_mime_expr_parse src/libmime/mime_expressions.c:809
    #6 0x7fa30a0a4294 in rspamd_parse_expression src/libutil/expression.c:923
    #7 0x7fa309bdcee9 in read_regexp_expression src/plugins/regexp.c:81
    #8 0x7fa309bddf63 in regexp_module_config src/plugins/regexp.c:230
    #9 0x7fa30a049035 in rspamd_init_filters src/libserver/cfg_utils.c:1498
    #10 0x7fa309c4fa8a in lua_config_init_modules src/lua/lua_config.c:4364
    #11 0x7fa30a0dcb14 in lj_BC_FUNCC (/usr/lib/rspamd/librspamd-server.so+0xb0eb14)

Direct leak of 20 byte(s) in 2 object(s) allocated from:
    #0 0x56171c8dc2c8 in __interceptor_malloc (/usr/bin/rspamadm+0x1592c8)
    #1 0x7fa3090a0e98 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x57e98)
    #2 0x7fa30a0712fc in rspamd_upstreams_add_upstream src/libutil/upstream.c:1090
    #3 0x7fa30a0720d1 in rspamd_upstreams_parse_line_len src/libutil/upstream.c:1256
    #4 0x7fa30a0721cf in rspamd_upstreams_parse_line src/libutil/upstream.c:1285
    #5 0x7fa309c3b513 in lua_upstream_list_create src/lua/lua_upstream.c:325
    #6 0x7fa30a0dcb14 in lj_BC_FUNCC (/usr/lib/rspamd/librspamd-server.so+0xb0eb14)

SUMMARY: AddressSanitizer: 308 byte(s) leaked in 5 allocation(s).
```

**Comment by devfbe** [comment]
Got this issue too with stable repo and ubuntu stable lts (focal, Ubuntu 20.04 LTS)

**Comment by pompfe** [comment]
Same for me on focal.  segfaults on stable and leaks messages on asan.

**Comment by ben221199** [comment]
The draft `draft-brand-indicators-for-message-identification-08` contains the following text:
> BIMI relies on these authentication protocols, but is not a new authentication protocol itself.

This means that, contrary to SPF, DKIM and DMARC, BIMI should not be used as authentication protocol. Passing or failing for BIMI should not have any effect, except having a logo (or not) visible in your mail program or webmail.
