### ISSUE TITLE
[BUG] Gtube crashes controller worker on fuzzy hash calculation

### ISSUE THREAD

**Issue by dasJ** [rspamd/rspamd#5074]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Passing a gtube test mail causes the Rspamd process to crash. I assume this is because of the passthrough module somewhat?

### Steps to Reproduce

1. Open the scan web interface
2. Paste gtube mail [from german Wikipedia](https://de.wikipedia.org/wiki/GTUBE)
3. Press "Compute fuzzy hashes"

**Expected behavior**

The process should not crash

### Versions

Rspamd daemon version 3.8.4

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1693350652)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

NixOS 24.05 on x86_64

### Additional Information

```
<b5fb3d>; csession; rspamd_message_parse: loaded message; id: <GTUBE1.1010101@example.net>; queue-id: <undef>; size: 797; checksum: <84e2fe6aaebaeb3ec87b7cbf5ccdb5ee>
<b5fb3d>; csession; rspamd_check_gtube: gtube reject pattern has been found in part of length 503
<b5fb3d>; csession; rspamd_add_passthrough_result: <GTUBE1.1010101@example.net>: set pre-result to 'reject' (15.00): 'Gtube pattern' from GTUBE(3)
<>; ; rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 292658, trace:
<>; ; log_backtrace: #0: [0x71b6dc5f4f78]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so in rspamd::log_backtrace()
<>; ; log_backtrace: #1: [0x71b6dc5bb8b8]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so in
<>; ; log_backtrace: #2: [0x71b6d8052f2f]: /nix/store/dbcw19dshdwnxdv5q2g6wldj6syyvq7l-glibc-2.39-52/lib/libc.so.6 in
<>; ; log_backtrace: #3: [0x71b6dc69f189]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so in
<>; ; log_backtrace: #4: [0x71b6dca48a35]: /nix/store/8apx02hrz7bb9pmhcw88dj2k6jgj7pxl-luajit-2.1.1693350652/lib/libluajit-5.1.so.2 in
<>; ; log_backtrace: #5: [0x71b6dcaa3afb]: /nix/store/8apx02hrz7bb9pmhcw88dj2k6jgj7pxl-luajit-2.1.1693350652/lib/libluajit-5.1.so.2 in lua_pcall
<>; ; log_backtrace: #6: [0x71b6dc6cd991]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so in
<>; ; log_backtrace: #7: [0x71b6dc6ce660]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so in
<>; ; log_backtrace: #8: [0x71b6dca48a35]: /nix/store/8apx02hrz7bb9pmhcw88dj2k6jgj7pxl-luajit-2.1.1693350652/lib/libluajit-5.1.so.2 in
<>; ; log_backtrace: #9: [0x71b6dcaa3afb]: /nix/store/8apx02hrz7bb9pmhcw88dj2k6jgj7pxl-luajit-2.1.1693350652/lib/libluajit-5.1.so.2 in lua_pcall
<>; ; log_backtrace: #10: [0x5a7e2e8ab3fd]: rspamd: controller process  in /run/rspamd/controller.sock mode=0666 owner=rspamd group=rspamd
<>; ; log_backtrace: #11: [0x71b6dc5c5eec]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so in
<>; ; log_backtrace: #12: [0x71b6dc5c7ebb]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so in
<>; ; log_backtrace: #13: [0x71b6dc6e0c7d]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so in http_parser_execute
<>; ; log_backtrace: #14: [0x71b6dc5c3855]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so in
<>; ; log_backtrace: #15: [0x71b6dcaf5e05]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-ev.so in ev_invoke_pending
<>; ; log_backtrace: #16: [0x71b6dcaf95dc]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-ev.so in ev_run
<>; ; log_backtrace: #17: [0x5a7e2e8abc70]: rspamd: controller process  in /run/rspamd/controller.sock mode=0666 owner=rspamd group=rspamd
<>; ; log_backtrace: #18: [0x71b6dc5baf13]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so in rspamd_fork_worker
<>; ; log_backtrace: #19: [0x5a7e2e8b35ae]: rspamd: controller process  in /run/rspamd/controller.sock mode=0666 owner=rspamd group=rspamd
<>; ; log_backtrace: #20: [0x71b6dcaf5e05]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-ev.so in ev_invoke_pending
<>; ; log_backtrace: #21: [0x71b6dcaf95dc]: /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-ev.so in ev_run
<>; ; log_backtrace: #22: [0x5a7e2e8a3cd2]: rspamd: controller process  in /run/rspamd/controller.sock mode=0666 owner=rspamd group=rspamd
<>; ; log_backtrace: #23: [0x71b6d803d10d]: /nix/store/dbcw19dshdwnxdv5q2g6wldj6syyvq7l-glibc-2.39-52/lib/libc.so.6 in
<>; ; log_backtrace: #24: [0x71b6d803d1c8]: /nix/store/dbcw19dshdwnxdv5q2g6wldj6syyvq7l-glibc-2.39-52/lib/libc.so.6 in __libc_start_main
<>; ; log_backtrace: #25: [0x5a7e2e8a4274]: rspamd: controller process  in /run/rspamd/controller.sock mode=0666 owner=rspamd group=rspamd
<>; ; log_backtrace: #26: [0xffffffffffffffff]: [0xffffffffffffffff] in
<>; ; rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
<cdf59e>; main; rspamd_srv_handler: cannot read from worker's srv pipe connection closed; command = heartbeat
```

```
Core was generated by `rspamd: controller process (/run/rspamd/controller.sock mode=0666 owner=rspamd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000071b6dc69f189 in lua_textpart_get_content_oneline.lto_priv () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so
(gdb) bt
#0  0x000071b6dc69f189 in lua_textpart_get_content_oneline.lto_priv () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so
#1  0x000071b6dca48a36 in ?? () from /nix/store/8apx02hrz7bb9pmhcw88dj2k6jgj7pxl-luajit-2.1.1693350652/lib/libluajit-5.1.so.2
#2  0x000071b6dcaa3afc in lua_pcall () from /nix/store/8apx02hrz7bb9pmhcw88dj2k6jgj7pxl-luajit-2.1.1693350652/lib/libluajit-5.1.so.2
#3  0x000071b6dc6cd992 in fuzzy_generate_commands () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so
#4  0x000071b6dc6ce661 in fuzzy_lua_hex_hashes_handler () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so
#5  0x000071b6dca48a36 in ?? () from /nix/store/8apx02hrz7bb9pmhcw88dj2k6jgj7pxl-luajit-2.1.1693350652/lib/libluajit-5.1.so.2
#6  0x000071b6dcaa3afc in lua_pcall () from /nix/store/8apx02hrz7bb9pmhcw88dj2k6jgj7pxl-luajit-2.1.1693350652/lib/libluajit-5.1.so.2
#7  0x00005a7e2e8ab3fe in rspamd_controller_handle_lua_plugin ()
#8  0x000071b6dc5c5eed in rspamd_http_router_finish_handler () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so
#9  0x000071b6dc5c7ebc in rspamd_http_on_message_complete.lto_priv () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so
#10 0x000071b6dc6e0c7e in http_parser_execute () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so
#11 0x000071b6dc5c3856 in rspamd_http_event_handler () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so
#12 0x000071b6dcaf5e06 in ev_invoke_pending () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-ev.so
#13 0x000071b6dcaf95dd in ev_run () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-ev.so
#14 0x00005a7e2e8abc71 in start_controller_worker ()
#15 0x000071b6dc5baf14 in rspamd_fork_worker () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-server.so
#16 0x00005a7e2e8b35af in rspamd_fork_delayed_cb ()
#17 0x000071b6dcaf5e06 in ev_invoke_pending () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-ev.so
#18 0x000071b6dcaf95dd in ev_run () from /nix/store/yb92idd5akyb41w52vcz2v1jd7xibkvw-rspamd-3.8.4/lib/rspamd/librspamd-ev.so
#19 0x00005a7e2e8a3cd3 in main ()
```

**Comment by vstakhov** [comment]
I'm sorry, but there is no support for outdated versions of Rspamd. Update to the supported version and try to reproduce.
