### ISSUE TITLE
Segmentation fault (rspamd: normal process)

### ISSUE THREAD

**Issue by AlexeySa** [rspamd/rspamd#670]
Rspamd v.1.2.7 (git version 09/06/2016 11:08 MSK)

```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f74e5526301 in __strlen_sse2 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install file-libs-5.04-30.el6.x86_64 glibc-2.12-1.192.el6.x86_64 keyutils-lib-1.4-5.el6.x86_64 krb5-libs-1.10.3-57.el6.x86_64 libcom_err-1.41.12-22.el6.x86_64 libffi-3.0.5-3.2.el6.x86_64 libgcc-4.4.-17.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 openssl-1.0.1e-48.el6_8.1.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x00007f74e5526301 in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00007f74e432fc52 in ?? () from /usr/local/rspamd/lib/rspamd/libluajit-5.1.so.2
#2  0x0000000000474ffb in lua_tcp_push_error (cbd=0x6d6f632e75726d, err=0x51e3ac "")
    at /root/src/rspamd/rspamd-1.2.7/src/lua/lua_tcp.c:130
#3  0x0000000000475593 in lua_tcp_dns_handler (reply=0x6d6f632e75726d, ud=<value optimized out>)
    at /root/src/rspamd/rspamd-1.2.7/src/lua/lua_tcp.c:364
#4  0x0000000001115930 in ?? ()
#5  0x000000000108cfb0 in ?? ()
#6  0x0000000000485d1b in rspamd_dns_fin_cb (arg=0x7fff9caaf0b0) at /root/src/rspamd/rspamd-1.2.7/src/libserver/dns.c:55
#7  0x0000000001117950 in ?? ()
#8  0x00007fff9caaf0b0 in ?? ()
#9  0x00000000005037f0 in rdns_process_read (fd=<value optimized out>, arg=<value optimized out>)
    at /root/src/rspamd/rspamd-1.2.7/contrib/librdns/resolver.c:273
#10 0x00007f74e5b151d5 in event_persist_closure (base=0x107de90, flags=0) at event.c:1319
#11 event_process_active_single_queue (base=0x107de90, flags=0) at event.c:1363
#12 event_process_active (base=0x107de90, flags=0) at event.c:1438
#13 event_base_loop (base=0x107de90, flags=0) at event.c:1639
#14 0x000000000042df22 in start_worker (worker=0x1018040) at /root/src/rspamd/rspamd-1.2.7/src/worker.c:514
#15 0x00000000004989bf in rspamd_fork_worker (rspamd_main=0xd1ff50, cf=0x107db90, index=<value optimized out>,
    ev_base=0x105cc90) at /root/src/rspamd/rspamd-1.2.7/src/libserver/worker_util.c:556
#16 0x000000000042c276 in rspamd_cld_handler (signo=<value optimized out>, what=<value optimized out>, arg=0x105dca0)
    at /root/src/rspamd/rspamd-1.2.7/src/rspamd.c:890
#17 0x00007f74e5d46700 in pollops () from /usr/local/rspamd/lib/rspamd/libevent-2.0.so.5
#18 0x000000000105ce00 in ?? ()
#19 0x000000000105ce20 in ?? ()
#20 0x646d617000007f00 in ?? ()
#21 0x0000000000d1ff50 in ?? ()
#22 0x0000000000427939 in fuzzy_peer_rep (worker=0x6d6f632e75726d, rep=0x4040f410, rep_fd=24, ud=0x2d)
    at /root/src/rspamd/rspamd-1.2.7/src/fuzzy_storage.c:1358
#23 0x0000000000000000 in ?? ()
```

**Comment by AlexeySa** [comment]
This problem is present when disable Ipv6 in my system.
