### ISSUE TITLE
rspamd accidentally crashes

### ISSUE THREAD

**Issue by drook** [rspamd/rspamd#688]
Rspamd 1.2.0
FreeBSD 10-STABLE

I have a bunch of cores from tonight, they look pretty similar.
Backtraces follows:

``` bt1
# gdb /usr/local/bin/rspamd rspamd-1.2.0.65534.10002.core 
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...

warning: core file may not match specified executable file.
Core was generated by `rspamd-1.2.0'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /usr/local/lib/libhs.so.4.1...done.
Loaded symbols for /usr/local/lib/libhs.so.4.1
Reading symbols from /lib/libutil.so.9...done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libgmodule-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgmodule-2.0.so.0
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libgmime-2.4.so.2...done.
Loaded symbols for /usr/local/lib/libgmime-2.4.so.2
Reading symbols from /usr/local/lib/libgobject-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgobject-2.0.so.0
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libevent-2.0.so.5...done.
Loaded symbols for /usr/local/lib/libevent-2.0.so.5
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /lib/libcrypto.so.7...done.
Loaded symbols for /lib/libcrypto.so.7
Reading symbols from /usr/lib/libmagic.so.4...done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /usr/lib/libc++.so.1...done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/libz.so.6...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /usr/local/lib/libffi.so.6...done.
Loaded symbols for /usr/local/lib/libffi.so.6
Reading symbols from /usr/local/lib/nss_winbind.so.1...done.
Loaded symbols for /usr/local/lib/nss_winbind.so.1
Reading symbols from /usr/local/lib/samba/libwinbind-client-samba4.so...done.
Loaded symbols for /usr/local/lib/samba/libwinbind-client-samba4.so
Reading symbols from /usr/local/lib/samba/libreplace-samba4.so...done.
Loaded symbols for /usr/local/lib/samba/libreplace-samba4.so
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  redisAsyncFree (ac=0x0) at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:325
325     /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c: No such file or directory.
        in /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c
[New Thread 805406400 (LWP 101095/<unknown>)]
(gdb) bt
#0  redisAsyncFree (ac=0x0) at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:325
#1  0x00000000004ef0f7 in rspamd_redis_async_cbdata_cleanup (cbdata=0x8056d1200)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/libstat/backends/redis_backend.c:429
#2  0x00000000004ef6e4 in rspamd_redis_stat_keys (c=0x8054ddc80, r=0x0, priv=0x8056d1200)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/libstat/backends/redis_backend.c:612
#3  0x000000000056f512 in __redisAsyncFree (ac=0x8054ddc80)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:269
#4  0x000000000056ff92 in redisAsyncHandleWrite (ac=<value optimized out>)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:348
#5  0x00000000004ef0ca in redisLibeventWriteEvent (fd=31, event=4, arg=0x8055d4700) at libevent.h:51
#6  0x0000000802856aed in event_process_active_single_queue (base=0x805552980, activeq=0x80571bde0) at event.c:1368
#7  0x000000080285267c in event_process_active (base=0x805552980) at event.c:1438
#8  0x00000008028516ff in event_base_loop (base=0x805552980, flags=0) at event.c:1639
#9  0x000000000042648a in start_controller_worker (worker=0x805770600)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/controller.c:2663
#10 0x00000000004df61a in rspamd_fork_worker (rspamd_main=0x805458080, cf=0x8057786e0, index=0, ev_base=0x805552980)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/libserver/worker_util.c:549
#11 0x0000000000435300 in rspamd_fork_delayed_cb (signo=-1, what=1, arg=0x8056180c0)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/rspamd.c:309
#12 0x0000000802856aed in event_process_active_single_queue (base=0x805552980, activeq=0x80571bde0) at event.c:1368
#13 0x000000080285267c in event_process_active (base=0x805552980) at event.c:1438
#14 0x00000008028516ff in event_base_loop (base=0x805552980, flags=0) at event.c:1639
#15 0x0000000000432cb9 in main (argc=1, argv=0x7fffffffeb80, env=0x7fffffffebc0)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/rspamd.c:1232
Current language:  auto; currently minimal
(gdb)
```

``` bt2
# gdb /usr/local/bin/rspamd rspamd-1.2.0.65534.10157.core 
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...

warning: core file may not match specified executable file.
Core was generated by `rspamd-1.2.0'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /usr/local/lib/libhs.so.4.1...done.
Loaded symbols for /usr/local/lib/libhs.so.4.1
Reading symbols from /lib/libutil.so.9...done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libgmodule-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgmodule-2.0.so.0
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libgmime-2.4.so.2...done.
Loaded symbols for /usr/local/lib/libgmime-2.4.so.2
Reading symbols from /usr/local/lib/libgobject-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgobject-2.0.so.0
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libevent-2.0.so.5...done.
Loaded symbols for /usr/local/lib/libevent-2.0.so.5
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /lib/libcrypto.so.7...done.
Loaded symbols for /lib/libcrypto.so.7
Reading symbols from /usr/lib/libmagic.so.4...done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /usr/lib/libc++.so.1...done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/libz.so.6...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /usr/local/lib/libffi.so.6...done.
Loaded symbols for /usr/local/lib/libffi.so.6
Reading symbols from /usr/local/lib/nss_winbind.so.1...done.
Loaded symbols for /usr/local/lib/nss_winbind.so.1
Reading symbols from /usr/local/lib/samba/libwinbind-client-samba4.so...done.
Loaded symbols for /usr/local/lib/samba/libwinbind-client-samba4.so
Reading symbols from /usr/local/lib/samba/libreplace-samba4.so...done.
Loaded symbols for /usr/local/lib/samba/libreplace-samba4.so
Reading symbols from /usr/lib/i18n/libiconv_std.so.4...done.
Loaded symbols for /usr/lib/i18n/libiconv_std.so.4
Reading symbols from /usr/lib/i18n/libUTF8.so.4...done.
Loaded symbols for /usr/lib/i18n/libUTF8.so.4
Reading symbols from /usr/lib/i18n/libmapper_parallel.so.4...done.
Loaded symbols for /usr/lib/i18n/libmapper_parallel.so.4
Reading symbols from /usr/lib/i18n/libmapper_std.so.4...done.
Loaded symbols for /usr/lib/i18n/libmapper_std.so.4
Reading symbols from /usr/lib/i18n/libmapper_zone.so.4...done.
Loaded symbols for /usr/lib/i18n/libmapper_zone.so.4
Reading symbols from /usr/lib/i18n/libmapper_none.so.4...done.
Loaded symbols for /usr/lib/i18n/libmapper_none.so.4
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  redisAsyncFree (ac=0x0) at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:325
325     /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c: No such file or directory.
        in /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c
[New Thread 805406400 (LWP 100901/<unknown>)]
(gdb) bt
#0  redisAsyncFree (ac=0x0) at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:325
#1  0x00000000004ef0f7 in rspamd_redis_async_cbdata_cleanup (cbdata=0x8056d1240)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/libstat/backends/redis_backend.c:429
#2  0x00000000004ef6e4 in rspamd_redis_stat_keys (c=0x8054ddc80, r=0x0, priv=0x8056d1240)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/libstat/backends/redis_backend.c:612
#3  0x000000000056f512 in __redisAsyncFree (ac=0x8054ddc80)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:269
#4  0x000000000056ff92 in redisAsyncHandleWrite (ac=<value optimized out>)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:348
#5  0x00000000004ef0ca in redisLibeventWriteEvent (fd=30, event=4, arg=0x8055d4700) at libevent.h:51
#6  0x0000000802856aed in event_process_active_single_queue (base=0x805552980, activeq=0x80571bde0) at event.c:1368
#7  0x000000080285267c in event_process_active (base=0x805552980) at event.c:1438
#8  0x00000008028516ff in event_base_loop (base=0x805552980, flags=0) at event.c:1639
#9  0x0000000000438bb5 in start_worker (worker=0x805770300)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/worker.c:488
#10 0x00000000004df61a in rspamd_fork_worker (rspamd_main=0x805458080, cf=0x8057787a0, index=0, ev_base=0x805552980)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/libserver/worker_util.c:549
#11 0x0000000000435300 in rspamd_fork_delayed_cb (signo=-1, what=1, arg=0x805618160)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/rspamd.c:309
#12 0x0000000802856aed in event_process_active_single_queue (base=0x805552980, activeq=0x80571bde0) at event.c:1368
#13 0x000000080285267c in event_process_active (base=0x805552980) at event.c:1438
#14 0x00000008028516ff in event_base_loop (base=0x805552980, flags=0) at event.c:1639
#15 0x0000000000432cb9 in main (argc=1, argv=0x7fffffffeb80, env=0x7fffffffebc0)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/rspamd.c:1232
Current language:  auto; currently minimal
(gdb)
```

``` bt3
# gdb /usr/local/bin/rspamd rspamd-1.2.0.65534.10159.core 
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...

warning: core file may not match specified executable file.
Core was generated by `rspamd-1.2.0'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /usr/local/lib/libhs.so.4.1...done.
Loaded symbols for /usr/local/lib/libhs.so.4.1
Reading symbols from /lib/libutil.so.9...done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libgmodule-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgmodule-2.0.so.0
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libgmime-2.4.so.2...done.
Loaded symbols for /usr/local/lib/libgmime-2.4.so.2
Reading symbols from /usr/local/lib/libgobject-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgobject-2.0.so.0
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libevent-2.0.so.5...done.
Loaded symbols for /usr/local/lib/libevent-2.0.so.5
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /lib/libcrypto.so.7...done.
Loaded symbols for /lib/libcrypto.so.7
Reading symbols from /usr/lib/libmagic.so.4...done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /usr/lib/libc++.so.1...done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/libz.so.6...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /usr/local/lib/libffi.so.6...done.
Loaded symbols for /usr/local/lib/libffi.so.6
Reading symbols from /usr/local/lib/nss_winbind.so.1...done.
Loaded symbols for /usr/local/lib/nss_winbind.so.1
Reading symbols from /usr/local/lib/samba/libwinbind-client-samba4.so...done.
Loaded symbols for /usr/local/lib/samba/libwinbind-client-samba4.so
Reading symbols from /usr/local/lib/samba/libreplace-samba4.so...done.
Loaded symbols for /usr/local/lib/samba/libreplace-samba4.so
Reading symbols from /usr/lib/i18n/libiconv_std.so.4...done.
Loaded symbols for /usr/lib/i18n/libiconv_std.so.4
Reading symbols from /usr/lib/i18n/libUTF8.so.4...done.
Loaded symbols for /usr/lib/i18n/libUTF8.so.4
Reading symbols from /usr/lib/i18n/libmapper_parallel.so.4...done.
Loaded symbols for /usr/lib/i18n/libmapper_parallel.so.4
Reading symbols from /usr/lib/i18n/libmapper_std.so.4...done.
Loaded symbols for /usr/lib/i18n/libmapper_std.so.4
Reading symbols from /usr/lib/i18n/libmapper_zone.so.4...done.
Loaded symbols for /usr/lib/i18n/libmapper_zone.so.4
Reading symbols from /usr/lib/i18n/libmapper_none.so.4...done.
Loaded symbols for /usr/lib/i18n/libmapper_none.so.4
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  redisAsyncFree (ac=0x0) at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:325
325     /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c: No such file or directory.
        in /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c
[New Thread 805406400 (LWP 102185/<unknown>)]
(gdb) bt
#0  redisAsyncFree (ac=0x0) at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:325
#1  0x00000000004ef0f7 in rspamd_redis_async_cbdata_cleanup (cbdata=0x8056d1210)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/libstat/backends/redis_backend.c:429
#2  0x00000000004ef6e4 in rspamd_redis_stat_keys (c=0x8054ddb00, r=0x0, priv=0x8056d1210)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/libstat/backends/redis_backend.c:612
#3  0x000000000056f512 in __redisAsyncFree (ac=0x8054ddb00)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:269
#4  0x000000000056ff92 in redisAsyncHandleWrite (ac=<value optimized out>)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/contrib/hiredis/async.c:348
#5  0x00000000004ef0ca in redisLibeventWriteEvent (fd=31, event=4, arg=0x8055d45c0) at libevent.h:51
#6  0x0000000802856aed in event_process_active_single_queue (base=0x805552980, activeq=0x80571bde0) at event.c:1368
#7  0x000000080285267c in event_process_active (base=0x805552980) at event.c:1438
#8  0x00000008028516ff in event_base_loop (base=0x805552980, flags=0) at event.c:1639
#9  0x0000000000438bb5 in start_worker (worker=0x805770500)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/worker.c:488
#10 0x00000000004df61a in rspamd_fork_worker (rspamd_main=0x805458080, cf=0x805778740, index=3, ev_base=0x805552980)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/libserver/worker_util.c:549
#11 0x0000000000435300 in rspamd_fork_delayed_cb (signo=-1, what=1, arg=0x805618200)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/rspamd.c:309
#12 0x0000000802856aed in event_process_active_single_queue (base=0x805552980, activeq=0x80571bde0) at event.c:1368
#13 0x000000080285267c in event_process_active (base=0x805552980) at event.c:1438
#14 0x00000008028516ff in event_base_loop (base=0x805552980, flags=0) at event.c:1639
#15 0x0000000000432cb9 in main (argc=1, argv=0x7fffffffeb80, env=0x7fffffffebc0)
    at /usr/ports/mail/rspamd-devel/work/rspamd-3ba7a3c/src/rspamd.c:1232
Current language:  auto; currently minimal
(gdb)
```

And so on, I have like dozens of them. To be honest, this can be related to the fact that my redis host recently lost half of it's memory, and while new memory is still on the way from Taiwan (hopefully, not on foot) it became rather slow sometimes. But I doubt rspamd shoudl crash even in this case.

**Comment by AloneShadow** [comment]
Rspamd-1.2.8 on FreeBSD 11.0-ALPHA6 r302332: amd64 but in chroot environment has the same behavior.

```
Core was generated by `rspamd-1.2.8'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /lib/libutil.so.9...Reading symbols from /usr/lib/debug//lib/libutil.so.9.debug...done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libgmodule-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgmodule-2.0.so.0
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libgmime-2.4.so.2...done.
Loaded symbols for /usr/local/lib/libgmime-2.4.so.2
Reading symbols from /usr/local/lib/libgobject-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgobject-2.0.so.0
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libevent-2.0.so.5...done.
Loaded symbols for /usr/local/lib/libevent-2.0.so.5
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /lib/libcrypto.so.8...Reading symbols from /usr/lib/debug//lib/libcrypto.so.8.debug...done.
Loaded symbols for /lib/libcrypto.so.8
Reading symbols from /usr/lib/libmagic.so.4...Reading symbols from /usr/lib/debug//usr/lib/libmagic.so.4.debug...done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libthr.so.3...Reading symbols from /usr/lib/debug//lib/libthr.so.3.debug...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libm.so.5...Reading symbols from /usr/lib/debug//lib/libm.so.5.debug...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /lib/libc.so.7...Reading symbols from /usr/lib/debug//lib/libc.so.7.debug...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /lib/libz.so.6...Reading symbols from /usr/lib/debug//lib/libz.so.6.debug...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /usr/local/lib/libffi.so.6...done.
Loaded symbols for /usr/local/lib/libffi.so.6
Reading symbols from /lib/libgcc_s.so.1...Reading symbols from /usr/lib/debug//lib/libgcc_s.so.1.debug...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /usr/lib/i18n/libiconv_std.so.4...Reading symbols from /usr/lib/debug//usr/lib/i18n/libiconv_std.so.4.debug...done.
Loaded symbols for /usr/lib/i18n/libiconv_std.so.4
Reading symbols from /usr/lib/i18n/libUTF8.so.4...Reading symbols from /usr/lib/debug//usr/lib/i18n/libUTF8.so.4.debug...done.
Loaded symbols for /usr/lib/i18n/libUTF8.so.4
Reading symbols from /usr/lib/i18n/libmapper_std.so.4...Reading symbols from /usr/lib/debug//usr/lib/i18n/libmapper_std.so.4.debug...done.
Loaded symbols for /usr/lib/i18n/libmapper_std.so.4
Reading symbols from /usr/lib/i18n/libmapper_parallel.so.4...Reading symbols from /usr/lib/debug//usr/lib/i18n/libmapper_parallel.so.4.debug...done.
Loaded symbols for /usr/lib/i18n/libmapper_parallel.so.4
Reading symbols from /usr/lib/i18n/libmapper_none.so.4...Reading symbols from /usr/lib/debug//usr/lib/i18n/libmapper_none.so.4.debug...done.
Loaded symbols for /usr/lib/i18n/libmapper_none.so.4
Reading symbols from /usr/lib/i18n/libmapper_646.so.4...Reading symbols from /usr/lib/debug//usr/lib/i18n/libmapper_646.so.4.debug...done.
Loaded symbols for /usr/lib/i18n/libmapper_646.so.4
Reading symbols from /usr/lib/i18n/libGBK2K.so.4...Reading symbols from /usr/lib/debug//usr/lib/i18n/libGBK2K.so.4.debug...done.
Loaded symbols for /usr/lib/i18n/libGBK2K.so.4
Reading symbols from /usr/lib/i18n/libEUC.so.4...Reading symbols from /usr/lib/debug//usr/lib/i18n/libEUC.so.4.debug...done.
Loaded symbols for /usr/lib/i18n/libEUC.so.4
Reading symbols from /libexec/ld-elf.so.1...Reading symbols from /usr/lib/debug//libexec/ld-elf.so.1.debug...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x00000008034bab54 in memmove () from /lib/libc.so.7
[New Thread 804016000 (LWP 106277/<unknown>)]
(gdb) bt
#0  0x00000008034bab54 in memmove () from /lib/libc.so.7
#1  0x0000000800e0d11b in g_strchug () from /usr/local/lib/libglib-2.0.so.0
#2  0x00000000004ad693 in rspamd_message_parse ()
#3  0x000000000049c13c in rspamd_task_process ()
#4  0x000000000049c12c in rspamd_task_process ()
#5  0x000000000049c12c in rspamd_task_process ()
#6  0x0000000000432b94 in start_worker ()
#7  0x000000000045302b in rspamd_http_date_format ()
#8  0x0000000000517bbb in http_parser_execute ()
#9  0x00000000004509da in rspamd_http_new_message ()
#10 0x0000000801dec3b5 in event_base_loop () from /usr/local/lib/libevent-2.0.so.5
#11 0x000000000043263f in start_worker ()
#12 0x00000000004a12c3 in rspamd_fork_worker ()
#13 0x000000000043083b in main ()

```
